import test from "node:test";
import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import { mountActivityPanel } from "./panel.mjs";

// Only the DOM operations used by the real mount are emulated. No replacement
// polling/controller implementation is tested, and no browser framework is needed.
class Element {
  constructor(tag, document) { this.tagName = tag; this.ownerDocument = document; this.children = []; this.listeners = new Map(); this.attributes = new Map(); this.text = ""; }
  set textContent(value) { this.text = String(value); this.children = []; }
  get textContent() { return this.text + this.children.map((child) => child.textContent).join(""); }
  append(...children) { this.children.push(...children); }
  replaceChildren(...children) { this.text = ""; this.children = children; }
  setAttribute(name, value) { this.attributes.set(name, value); }
  removeAttribute(name) { this.attributes.delete(name); }
  addEventListener(name, callback) { this.listeners.set(name, callback); }
  querySelectorAll(tag) { return this.children.flatMap((child) => [...(child.tagName === tag ? [child] : []), ...child.querySelectorAll(tag)]); }
  click() { if (!this.disabled) return this.listeners.get("click")?.({ preventDefault() {} }); }
}

const operationFile = process.env.ACTIVITY_UI_OPERATION_FIXTURE;
for (const manual of [false, true]) {
  test(`actual CRM success ${manual ? "manual" : "scheduled"} check stops polling and refreshes once`, { skip: !operationFile }, async (t) => {
    // Generated by TestOperationSuccessContractPreservesCompletedStorage after
    // real CRM Events PostgreSQL commits and application-boundary serialization.
    const operation = JSON.parse(await readFile(operationFile, "utf8"));
    assert.equal(operation.state, "succeeded", "the actual receiver must emit the one public success state");
    const timers = new Map(); let timerID = 0;
    const originalSetTimeout = globalThis.setTimeout, originalClearTimeout = globalThis.clearTimeout;
    globalThis.setTimeout = (callback) => { timers.set(++timerID, callback); return timerID; };
    globalThis.clearTimeout = (id) => timers.delete(id);
    t.after(() => { globalThis.setTimeout = originalSetTimeout; globalThis.clearTimeout = originalClearTimeout; });
    const document = { createElement(tag) { return new Element(tag, document); } };
    const element = document.createElement("div");
    let panelReads = 0, statusReads = 0, commandWrites = 0;
    const request = async ({ path, method }) => {
      if (path.includes("/panel?")) {
        panelReads++;
        return { status: 200, body: { users: [], timezone: "UTC", coverage: "unknown", data: { events: [], summaries: [], status: {} }, settings: { initial_days: 2, retention_days: 7 } } };
      }
      if (path.endsWith("/sync") && method === "POST") {
        commandWrites++;
        return { status: 202, body: { command_id: operation.command_id, operation_id: operation.id, state: "pending_delivery", delivery_state: "pending_delivery" } };
      }
      if (path.endsWith("/operations/" + operation.id)) {
        statusReads++;
        return { status: 200, body: { command_id: operation.command_id, operation_id: operation.id, state: operation.state, delivery_state: "accepted", operation } };
      }
      assert.fail(`unexpected request ${method} ${path}`);
    };
    const settle = () => new Promise((resolve) => setImmediate(resolve));
    const panel = mountActivityPanel(element, request);
    t.after(() => panel.destroy());
    await settle();
    assert.equal(panelReads, 1);
    const find = (text) => element.querySelectorAll("button").find((button) => button.textContent === text);
    await find("Синхронизировать").click();
    assert.equal(commandWrites, 1);
    assert.match(element.textContent, /ожидается доставка/);
    assert.equal(timers.size, 1);
    if (manual) {
      await find("Проверить операцию").click();
    } else {
      const [id, callback] = timers.entries().next().value;
      timers.delete(id); callback(); await settle();
    }
    assert.match(element.textContent, /Завершено/);
    assert.equal(statusReads, 1);
    assert.equal(panelReads, 2, "one refresh after the initial load");
    assert.equal(timers.size, 0, "no scheduled check remains after success");
    assert.equal(find("Проверить операцию").disabled, true);
    await find("Проверить операцию").click(); await settle();
    assert.equal(statusReads, 1);
    assert.equal(panelReads, 2);
  });
}
