// Code generated by api/proto/generate-adapters.py. DO NOT EDIT.
package servicerpc

import (
	"github.com/google/uuid"
	"github.com/sk1fy/amocrm-pro/internal/serviceapi"
	"github.com/sk1fy/amocrm-pro/internal/servicerpc/pb"
	"time"
)

func boundedInt32(v int) int32 {
	if v > 2147483647 {
		return 2147483647
	}
	if v < -2147483648 {
		return -2147483648
	}
	return int32(v)
}
func parseUUID(s string) uuid.UUID { id, _ := uuid.Parse(s); return id }
func parseTime(s string) time.Time { t, _ := time.Parse(time.RFC3339Nano, s); return t }
func toAuth(src serviceapi.Auth) *pb.Auth {
	out := new(pb.Auth)
	out.Token = src.Token
	return out
}
func fromAuth(src *pb.Auth) serviceapi.Auth {
	var out serviceapi.Auth
	if src == nil {
		return out
	}
	out.Token = src.Token
	return out
}
func toGrant(src serviceapi.Grant) *pb.Grant {
	out := new(pb.Grant)
	out.Audience = src.Audience
	out.Action = src.Action
	return out
}
func fromGrant(src *pb.Grant) serviceapi.Grant {
	var out serviceapi.Grant
	if src == nil {
		return out
	}
	out.Audience = src.Audience
	out.Action = src.Action
	return out
}
func toIssueRequest(src serviceapi.IssueRequest) *pb.IssueRequest {
	out := new(pb.IssueRequest)
	out.IntegrationId = src.IntegrationID.String()
	out.InstallationId = src.InstallationID.String()
	out.ActorId = src.ActorID
	out.System = src.System
	out.Consumer = src.Consumer
	out.RequestId = src.RequestID
	for _, item := range src.Grants {
		out.Grants = append(out.Grants, toGrant(item))
	}
	return out
}
func fromIssueRequest(src *pb.IssueRequest) serviceapi.IssueRequest {
	var out serviceapi.IssueRequest
	if src == nil {
		return out
	}
	out.IntegrationID = parseUUID(src.IntegrationId)
	out.InstallationID = parseUUID(src.InstallationId)
	out.ActorID = src.ActorId
	out.System = src.System
	out.Consumer = src.Consumer
	out.RequestID = src.RequestId
	for _, item := range src.Grants {
		out.Grants = append(out.Grants, fromGrant(item))
	}
	return out
}
func toPrincipal(src serviceapi.Principal) *pb.Principal {
	out := new(pb.Principal)
	out.IntegrationId = src.IntegrationID.String()
	out.InstallationId = src.InstallationID.String()
	out.ActorId = src.ActorID
	out.System = src.System
	out.Consumer = src.Consumer
	out.RequestId = src.RequestID
	out.ExpiresAt = src.ExpiresAt.Format(time.RFC3339Nano)
	return out
}
func fromPrincipal(src *pb.Principal) serviceapi.Principal {
	var out serviceapi.Principal
	if src == nil {
		return out
	}
	out.IntegrationID = parseUUID(src.IntegrationId)
	out.InstallationID = parseUUID(src.InstallationId)
	out.ActorID = src.ActorId
	out.System = src.System
	out.Consumer = src.Consumer
	out.RequestID = src.RequestId
	out.ExpiresAt = parseTime(src.ExpiresAt)
	return out
}
func toEvent(src serviceapi.Event) *pb.Event {
	out := new(pb.Event)
	out.Id = src.ID
	out.CreatedAt = src.CreatedAt
	out.CreatedBy = src.CreatedBy
	out.Type = src.Type
	out.EntityId = src.EntityID
	out.EntityType = src.EntityType
	out.ValueBefore = src.ValueBefore
	out.ValueAfter = src.ValueAfter
	return out
}
func fromEvent(src *pb.Event) serviceapi.Event {
	var out serviceapi.Event
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.CreatedAt = src.CreatedAt
	out.CreatedBy = src.CreatedBy
	out.Type = src.Type
	out.EntityID = src.EntityId
	out.EntityType = src.EntityType
	out.ValueBefore = src.ValueBefore
	out.ValueAfter = src.ValueAfter
	return out
}
func toEventPageRequest(src serviceapi.EventPageRequest) *pb.EventPageRequest {
	out := new(pb.EventPageRequest)
	out.Auth = toAuth(src.Auth)
	out.From = src.From
	out.To = src.To
	out.Page = boundedInt32(src.Page)
	out.Limit = boundedInt32(src.Limit)
	return out
}
func fromEventPageRequest(src *pb.EventPageRequest) serviceapi.EventPageRequest {
	var out serviceapi.EventPageRequest
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.From = src.From
	out.To = src.To
	out.Page = int(src.Page)
	out.Limit = int(src.Limit)
	return out
}
func toEventPage(src serviceapi.EventPage) *pb.EventPage {
	out := new(pb.EventPage)
	for _, item := range src.Events {
		out.Events = append(out.Events, toEvent(item))
	}
	out.HasNext = src.HasNext
	return out
}
func fromEventPage(src *pb.EventPage) serviceapi.EventPage {
	var out serviceapi.EventPage
	if src == nil {
		return out
	}
	for _, item := range src.Events {
		out.Events = append(out.Events, fromEvent(item))
	}
	out.HasNext = src.HasNext
	return out
}
func toUser(src serviceapi.User) *pb.User {
	out := new(pb.User)
	out.Id = src.ID
	out.Name = src.Name
	out.GroupId = src.GroupID
	out.GroupName = src.GroupName
	return out
}
func fromUser(src *pb.User) serviceapi.User {
	var out serviceapi.User
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.Name = src.Name
	out.GroupID = src.GroupId
	out.GroupName = src.GroupName
	return out
}
func toUsersRequest(src serviceapi.UsersRequest) *pb.UsersRequest {
	out := new(pb.UsersRequest)
	out.Auth = toAuth(src.Auth)
	out.UserIds = append(out.UserIds, src.UserIDs...)
	return out
}
func fromUsersRequest(src *pb.UsersRequest) serviceapi.UsersRequest {
	var out serviceapi.UsersRequest
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.UserIDs = append(out.UserIDs, src.UserIds...)
	return out
}
func toDirectory(src serviceapi.Directory) *pb.Directory {
	out := new(pb.Directory)
	for _, item := range src.Users {
		out.Users = append(out.Users, toUser(item))
	}
	out.Timezone = src.Timezone
	return out
}
func fromDirectory(src *pb.Directory) serviceapi.Directory {
	var out serviceapi.Directory
	if src == nil {
		return out
	}
	for _, item := range src.Users {
		out.Users = append(out.Users, fromUser(item))
	}
	out.Timezone = src.Timezone
	return out
}
func toQuery(src serviceapi.Query) *pb.Query {
	out := new(pb.Query)
	out.Auth = toAuth(src.Auth)
	out.From = src.From
	out.To = src.To
	out.UserIds = append(out.UserIds, src.UserIDs...)
	out.Limit = boundedInt32(src.Limit)
	out.Cursor = src.Cursor
	return out
}
func fromQuery(src *pb.Query) serviceapi.Query {
	var out serviceapi.Query
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.From = src.From
	out.To = src.To
	out.UserIDs = append(out.UserIDs, src.UserIds...)
	out.Limit = int(src.Limit)
	out.Cursor = src.Cursor
	return out
}
func toUserSummary(src serviceapi.UserSummary) *pb.UserSummary {
	out := new(pb.UserSummary)
	out.UserId = src.UserID
	out.UniqueEvents = src.UniqueEvents
	out.LastEventAt = src.LastEventAt
	return out
}
func fromUserSummary(src *pb.UserSummary) serviceapi.UserSummary {
	var out serviceapi.UserSummary
	if src == nil {
		return out
	}
	out.UserID = src.UserId
	out.UniqueEvents = src.UniqueEvents
	out.LastEventAt = src.LastEventAt
	return out
}
func toSyncStatus(src serviceapi.SyncStatus) *pb.SyncStatus {
	out := new(pb.SyncStatus)
	out.Enabled = src.Enabled
	out.State = src.State
	out.HistoryFrom = src.HistoryFrom
	out.VerifiedFrom = src.VerifiedFrom
	out.VerifiedThrough = src.VerifiedThrough
	out.WindowFrom = src.WindowFrom
	out.WindowTo = src.WindowTo
	out.NextPage = boundedInt32(src.NextPage)
	out.LastSuccessAt = src.LastSuccessAt
	out.LastEventAt = src.LastEventAt
	out.LagSeconds = src.LagSeconds
	out.ErrorCode = src.ErrorCode
	out.ReauthRequired = src.ReauthRequired
	out.Verification = src.Verification
	return out
}
func fromSyncStatus(src *pb.SyncStatus) serviceapi.SyncStatus {
	var out serviceapi.SyncStatus
	if src == nil {
		return out
	}
	out.Enabled = src.Enabled
	out.State = src.State
	out.HistoryFrom = src.HistoryFrom
	out.VerifiedFrom = src.VerifiedFrom
	out.VerifiedThrough = src.VerifiedThrough
	out.WindowFrom = src.WindowFrom
	out.WindowTo = src.WindowTo
	out.NextPage = int(src.NextPage)
	out.LastSuccessAt = src.LastSuccessAt
	out.LastEventAt = src.LastEventAt
	out.LagSeconds = src.LagSeconds
	out.ErrorCode = src.ErrorCode
	out.ReauthRequired = src.ReauthRequired
	out.Verification = src.Verification
	return out
}
func toQueryResult(src serviceapi.QueryResult) *pb.QueryResult {
	out := new(pb.QueryResult)
	for _, item := range src.Events {
		out.Events = append(out.Events, toEvent(item))
	}
	for _, item := range src.Summaries {
		out.Summaries = append(out.Summaries, toUserSummary(item))
	}
	out.NextCursor = src.NextCursor
	out.Status = toSyncStatus(src.Status)
	return out
}
func fromQueryResult(src *pb.QueryResult) serviceapi.QueryResult {
	var out serviceapi.QueryResult
	if src == nil {
		return out
	}
	for _, item := range src.Events {
		out.Events = append(out.Events, fromEvent(item))
	}
	for _, item := range src.Summaries {
		out.Summaries = append(out.Summaries, fromUserSummary(item))
	}
	out.NextCursor = src.NextCursor
	out.Status = fromSyncStatus(src.Status)
	return out
}
func toCommand(src serviceapi.Command) *pb.Command {
	out := new(pb.Command)
	out.Auth = toAuth(src.Auth)
	out.CommandId = src.CommandID
	out.Kind = src.Kind
	out.From = src.From
	out.To = src.To
	out.InitialDays = boundedInt32(src.InitialDays)
	out.RetentionDays = boundedInt32(src.RetentionDays)
	return out
}
func fromCommand(src *pb.Command) serviceapi.Command {
	var out serviceapi.Command
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.CommandID = src.CommandId
	out.Kind = src.Kind
	out.From = src.From
	out.To = src.To
	out.InitialDays = int(src.InitialDays)
	out.RetentionDays = int(src.RetentionDays)
	return out
}
func toOperation(src serviceapi.Operation) *pb.Operation {
	out := new(pb.Operation)
	out.Id = src.ID
	out.CommandId = src.CommandID
	out.State = src.State
	out.ErrorCode = src.ErrorCode
	out.Processed = src.Processed
	out.Inserted = src.Inserted
	out.Updated = src.Updated
	out.Deduplicated = src.Deduplicated
	return out
}
func fromOperation(src *pb.Operation) serviceapi.Operation {
	var out serviceapi.Operation
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.CommandID = src.CommandId
	out.State = src.State
	out.ErrorCode = src.ErrorCode
	out.Processed = src.Processed
	out.Inserted = src.Inserted
	out.Updated = src.Updated
	out.Deduplicated = src.Deduplicated
	return out
}
func toOperationRequest(src serviceapi.OperationRequest) *pb.OperationRequest {
	out := new(pb.OperationRequest)
	out.Auth = toAuth(src.Auth)
	out.OperationId = src.OperationID
	return out
}
func fromOperationRequest(src *pb.OperationRequest) serviceapi.OperationRequest {
	var out serviceapi.OperationRequest
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.OperationID = src.OperationId
	return out
}
func toSettings(src serviceapi.Settings) *pb.Settings {
	out := new(pb.Settings)
	out.InitialDays = boundedInt32(src.InitialDays)
	out.RetentionDays = boundedInt32(src.RetentionDays)
	return out
}
func fromSettings(src *pb.Settings) serviceapi.Settings {
	var out serviceapi.Settings
	if src == nil {
		return out
	}
	out.InitialDays = int(src.InitialDays)
	out.RetentionDays = int(src.RetentionDays)
	return out
}
func toSettingsCommand(src serviceapi.SettingsCommand) *pb.SettingsCommand {
	out := new(pb.SettingsCommand)
	out.Auth = toAuth(src.Auth)
	out.CommandId = src.CommandID
	out.Settings = toSettings(src.Settings)
	return out
}
func fromSettingsCommand(src *pb.SettingsCommand) serviceapi.SettingsCommand {
	var out serviceapi.SettingsCommand
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.CommandID = src.CommandId
	out.Settings = fromSettings(src.Settings)
	return out
}
func toPanel(src serviceapi.Panel) *pb.Panel {
	out := new(pb.Panel)
	for _, item := range src.Users {
		out.Users = append(out.Users, toUser(item))
	}
	out.Timezone = src.Timezone
	out.Data = toQueryResult(src.Data)
	out.Settings = toSettings(src.Settings)
	out.Coverage = src.Coverage
	return out
}
func fromPanel(src *pb.Panel) serviceapi.Panel {
	var out serviceapi.Panel
	if src == nil {
		return out
	}
	for _, item := range src.Users {
		out.Users = append(out.Users, fromUser(item))
	}
	out.Timezone = src.Timezone
	out.Data = fromQueryResult(src.Data)
	out.Settings = fromSettings(src.Settings)
	out.Coverage = src.Coverage
	return out
}
func toBootstrapAccountRequest(src serviceapi.BootstrapAccountRequest) *pb.BootstrapAccountRequest {
	out := new(pb.BootstrapAccountRequest)
	out.IntegrationId = src.IntegrationID.String()
	out.AccountDomain = src.AccountDomain
	out.AccessToken = src.AccessToken
	return out
}
func fromBootstrapAccountRequest(src *pb.BootstrapAccountRequest) serviceapi.BootstrapAccountRequest {
	var out serviceapi.BootstrapAccountRequest
	if src == nil {
		return out
	}
	out.IntegrationID = parseUUID(src.IntegrationId)
	out.AccountDomain = src.AccountDomain
	out.AccessToken = src.AccessToken
	return out
}
func toBootstrapAccount(src serviceapi.BootstrapAccount) *pb.BootstrapAccount {
	out := new(pb.BootstrapAccount)
	out.Id = src.ID
	out.Subdomain = src.Subdomain
	return out
}
func fromBootstrapAccount(src *pb.BootstrapAccount) serviceapi.BootstrapAccount {
	var out serviceapi.BootstrapAccount
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.Subdomain = src.Subdomain
	return out
}
