// Code generated by api/proto/generate-adapters.py. DO NOT EDIT.
package servicerpc

import (
	"github.com/google/uuid"
	"github.com/sk1fy/amocrm-pro/internal/serviceapi"
	"github.com/sk1fy/amocrm-pro/internal/servicerpc/pb"
	"time"
)

func boundedInt32(v int) int32 {
	if v > 2147483647 {
		return 2147483647
	}
	if v < -2147483648 {
		return -2147483648
	}
	return int32(v)
}
func parseUUID(s string) uuid.UUID { id, _ := uuid.Parse(s); return id }
func parseTime(s string) time.Time { t, _ := time.Parse(time.RFC3339Nano, s); return t }
func toAuth(src serviceapi.Auth) *pb.Auth {
	out := new(pb.Auth)
	out.Token = src.Token
	return out
}
func fromAuth(src *pb.Auth) serviceapi.Auth {
	var out serviceapi.Auth
	if src == nil {
		return out
	}
	out.Token = src.Token
	return out
}
func toGrant(src serviceapi.Grant) *pb.Grant {
	out := new(pb.Grant)
	out.Audience = src.Audience
	out.Action = src.Action
	return out
}
func fromGrant(src *pb.Grant) serviceapi.Grant {
	var out serviceapi.Grant
	if src == nil {
		return out
	}
	out.Audience = src.Audience
	out.Action = src.Action
	return out
}
func toIssueRequest(src serviceapi.IssueRequest) *pb.IssueRequest {
	out := new(pb.IssueRequest)
	out.IntegrationId = src.IntegrationID.String()
	out.InstallationId = src.InstallationID.String()
	out.ActorId = src.ActorID
	out.System = src.System
	out.Consumer = src.Consumer
	out.RequestId = src.RequestID
	for _, item := range src.Grants {
		out.Grants = append(out.Grants, toGrant(item))
	}
	out.Kind = src.Kind
	out.PanelId = src.PanelID.String()
	out.ViewKeyVersion = boundedInt32(src.ViewKeyVersion)
	return out
}
func fromIssueRequest(src *pb.IssueRequest) serviceapi.IssueRequest {
	var out serviceapi.IssueRequest
	if src == nil {
		return out
	}
	out.IntegrationID = parseUUID(src.IntegrationId)
	out.InstallationID = parseUUID(src.InstallationId)
	out.ActorID = src.ActorId
	out.System = src.System
	out.Consumer = src.Consumer
	out.RequestID = src.RequestId
	for _, item := range src.Grants {
		out.Grants = append(out.Grants, fromGrant(item))
	}
	out.Kind = src.Kind
	out.PanelID = parseUUID(src.PanelId)
	out.ViewKeyVersion = int(src.ViewKeyVersion)
	return out
}
func toPrincipal(src serviceapi.Principal) *pb.Principal {
	out := new(pb.Principal)
	out.IntegrationId = src.IntegrationID.String()
	out.InstallationId = src.InstallationID.String()
	out.ActorId = src.ActorID
	out.System = src.System
	out.Consumer = src.Consumer
	out.RequestId = src.RequestID
	out.ExpiresAt = src.ExpiresAt.Format(time.RFC3339Nano)
	out.Kind = src.Kind
	out.PanelId = src.PanelID.String()
	out.ViewKeyVersion = boundedInt32(src.ViewKeyVersion)
	return out
}
func fromPrincipal(src *pb.Principal) serviceapi.Principal {
	var out serviceapi.Principal
	if src == nil {
		return out
	}
	out.IntegrationID = parseUUID(src.IntegrationId)
	out.InstallationID = parseUUID(src.InstallationId)
	out.ActorID = src.ActorId
	out.System = src.System
	out.Consumer = src.Consumer
	out.RequestID = src.RequestId
	out.ExpiresAt = parseTime(src.ExpiresAt)
	out.Kind = src.Kind
	out.PanelID = parseUUID(src.PanelId)
	out.ViewKeyVersion = int(src.ViewKeyVersion)
	return out
}
func toEvent(src serviceapi.Event) *pb.Event {
	out := new(pb.Event)
	out.Id = src.ID
	out.CreatedAt = src.CreatedAt
	out.CreatedBy = src.CreatedBy
	out.Type = src.Type
	out.EntityId = src.EntityID
	out.EntityType = src.EntityType
	out.ValueBefore = src.ValueBefore
	out.ValueAfter = src.ValueAfter
	out.LinkedTalkContactId = src.LinkedTalkContactID
	for _, item := range src.Enrichment {
		out.Enrichment = append(out.Enrichment, toEnrichmentObject(item))
	}
	for _, item := range src.Names {
		out.Names = append(out.Names, toCatalogName(item))
	}
	if src.View != nil {
		out.View = toEventView(*src.View)
	}
	return out
}
func fromEvent(src *pb.Event) serviceapi.Event {
	var out serviceapi.Event
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.CreatedAt = src.CreatedAt
	out.CreatedBy = src.CreatedBy
	out.Type = src.Type
	out.EntityID = src.EntityId
	out.EntityType = src.EntityType
	out.ValueBefore = src.ValueBefore
	out.ValueAfter = src.ValueAfter
	out.LinkedTalkContactID = src.LinkedTalkContactId
	for _, item := range src.Enrichment {
		out.Enrichment = append(out.Enrichment, fromEnrichmentObject(item))
	}
	for _, item := range src.Names {
		out.Names = append(out.Names, fromCatalogName(item))
	}
	if src.View != nil && (src.View.Category != "" || src.View.Title != "" || src.View.Summary != "" || len(src.View.Details) > 0) {
		view := fromEventView(src.View)
		out.View = &view
	}
	return out
}
func toEventDetail(src serviceapi.EventDetail) *pb.EventDetail {
	out := new(pb.EventDetail)
	out.Key = src.Key
	out.Label = src.Label
	out.Before = src.Before
	out.After = src.After
	out.Text = src.Text
	out.Source = src.Source
	out.Current = src.Current
	return out
}
func fromEventDetail(src *pb.EventDetail) serviceapi.EventDetail {
	var out serviceapi.EventDetail
	if src == nil {
		return out
	}
	out.Key = src.Key
	out.Label = src.Label
	out.Before = src.Before
	out.After = src.After
	out.Text = src.Text
	out.Source = src.Source
	out.Current = src.Current
	return out
}
func toEventView(src serviceapi.EventView) *pb.EventView {
	out := new(pb.EventView)
	out.Category = src.Category
	out.Title = src.Title
	out.Summary = src.Summary
	out.DetailState = src.DetailState
	out.AuthorLabel = src.AuthorLabel
	out.EntityLabel = src.EntityLabel
	for _, item := range src.Details {
		out.Details = append(out.Details, toEventDetail(item))
	}
	out.EnrichmentState = src.EnrichmentState
	return out
}
func fromEventView(src *pb.EventView) serviceapi.EventView {
	var out serviceapi.EventView
	if src == nil {
		return out
	}
	out.Category = src.Category
	out.Title = src.Title
	out.Summary = src.Summary
	out.DetailState = src.DetailState
	out.AuthorLabel = src.AuthorLabel
	out.EntityLabel = src.EntityLabel
	for _, item := range src.Details {
		out.Details = append(out.Details, fromEventDetail(item))
	}
	out.EnrichmentState = src.EnrichmentState
	return out
}
func toCategoryCount(src serviceapi.CategoryCount) *pb.CategoryCount {
	out := new(pb.CategoryCount)
	out.Category = src.Category
	out.Count = src.Count
	return out
}
func fromCategoryCount(src *pb.CategoryCount) serviceapi.CategoryCount {
	var out serviceapi.CategoryCount
	if src == nil {
		return out
	}
	out.Category = src.Category
	out.Count = src.Count
	return out
}
func toTimeBucket(src serviceapi.TimeBucket) *pb.TimeBucket {
	out := new(pb.TimeBucket)
	out.StartAt = src.StartAt
	out.EndAt = src.EndAt
	out.Count = src.Count
	out.Coverage = src.Coverage
	return out
}
func fromTimeBucket(src *pb.TimeBucket) serviceapi.TimeBucket {
	var out serviceapi.TimeBucket
	if src == nil {
		return out
	}
	out.StartAt = src.StartAt
	out.EndAt = src.EndAt
	out.Count = src.Count
	out.Coverage = src.Coverage
	return out
}
func toQueryTotals(src serviceapi.QueryTotals) *pb.QueryTotals {
	out := new(pb.QueryTotals)
	out.UniqueEvents = src.UniqueEvents
	out.EntityCount = src.EntityCount
	out.TaskCompletedEvents = src.TaskCompletedEvents
	out.UniqueCompletedTasks = src.UniqueCompletedTasks
	out.FirstEventAt = src.FirstEventAt
	out.LastEventAt = src.LastEventAt
	for _, item := range src.CategoryCounts {
		out.CategoryCounts = append(out.CategoryCounts, toCategoryCount(item))
	}
	return out
}
func fromQueryTotals(src *pb.QueryTotals) serviceapi.QueryTotals {
	var out serviceapi.QueryTotals
	if src == nil {
		return out
	}
	out.UniqueEvents = src.UniqueEvents
	out.EntityCount = src.EntityCount
	out.TaskCompletedEvents = src.TaskCompletedEvents
	out.UniqueCompletedTasks = src.UniqueCompletedTasks
	out.FirstEventAt = src.FirstEventAt
	out.LastEventAt = src.LastEventAt
	for _, item := range src.CategoryCounts {
		out.CategoryCounts = append(out.CategoryCounts, fromCategoryCount(item))
	}
	return out
}
func toEnrichmentObject(src serviceapi.EnrichmentObject) *pb.EnrichmentObject {
	out := new(pb.EnrichmentObject)
	out.ObjectKind = src.ObjectKind
	out.ObjectKey = src.ObjectKey
	out.State = src.State
	out.ReasonCode = src.ReasonCode
	out.Source = src.Source
	out.FetchedAt = src.FetchedAt
	out.Payload = src.Payload
	out.Current = src.Current
	return out
}
func fromEnrichmentObject(src *pb.EnrichmentObject) serviceapi.EnrichmentObject {
	var out serviceapi.EnrichmentObject
	if src == nil {
		return out
	}
	out.ObjectKind = src.ObjectKind
	out.ObjectKey = src.ObjectKey
	out.State = src.State
	out.ReasonCode = src.ReasonCode
	out.Source = src.Source
	out.FetchedAt = src.FetchedAt
	out.Payload = src.Payload
	out.Current = src.Current
	return out
}
func toCatalogName(src serviceapi.CatalogName) *pb.CatalogName {
	out := new(pb.CatalogName)
	out.Kind = src.Kind
	out.Id = src.ID
	out.Name = src.Name
	out.State = src.State
	out.Current = src.Current
	out.EntityType = src.EntityType
	return out
}
func fromCatalogName(src *pb.CatalogName) serviceapi.CatalogName {
	var out serviceapi.CatalogName
	if src == nil {
		return out
	}
	out.Kind = src.Kind
	out.ID = src.Id
	out.Name = src.Name
	out.State = src.State
	out.Current = src.Current
	out.EntityType = src.EntityType
	return out
}
func toNotesRequest(src serviceapi.NotesRequest) *pb.NotesRequest {
	out := new(pb.NotesRequest)
	out.Auth = toAuth(src.Auth)
	out.EntityType = src.EntityType
	out.Ids = append(out.Ids, src.IDs...)
	return out
}
func fromNotesRequest(src *pb.NotesRequest) serviceapi.NotesRequest {
	var out serviceapi.NotesRequest
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.EntityType = src.EntityType
	out.IDs = append(out.IDs, src.Ids...)
	return out
}
func toNote(src serviceapi.Note) *pb.Note {
	out := new(pb.Note)
	out.Id = src.ID
	out.EntityId = src.EntityID
	out.EntityType = src.EntityType
	out.NoteType = src.NoteType
	out.CreatedBy = src.CreatedBy
	out.UpdatedAt = src.UpdatedAt
	out.Params = src.Params
	return out
}
func fromNote(src *pb.Note) serviceapi.Note {
	var out serviceapi.Note
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.EntityID = src.EntityId
	out.EntityType = src.EntityType
	out.NoteType = src.NoteType
	out.CreatedBy = src.CreatedBy
	out.UpdatedAt = src.UpdatedAt
	out.Params = src.Params
	return out
}
func toNotePage(src serviceapi.NotePage) *pb.NotePage {
	out := new(pb.NotePage)
	for _, item := range src.Notes {
		out.Notes = append(out.Notes, toNote(item))
	}
	out.InvalidIds = append(out.InvalidIds, src.InvalidIDs...)
	return out
}
func fromNotePage(src *pb.NotePage) serviceapi.NotePage {
	var out serviceapi.NotePage
	if src == nil {
		return out
	}
	for _, item := range src.Notes {
		out.Notes = append(out.Notes, fromNote(item))
	}
	out.InvalidIDs = append(out.InvalidIDs, src.InvalidIds...)
	return out
}
func toTasksRequest(src serviceapi.TasksRequest) *pb.TasksRequest {
	out := new(pb.TasksRequest)
	out.Auth = toAuth(src.Auth)
	out.Ids = append(out.Ids, src.IDs...)
	return out
}
func fromTasksRequest(src *pb.TasksRequest) serviceapi.TasksRequest {
	var out serviceapi.TasksRequest
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.IDs = append(out.IDs, src.Ids...)
	return out
}
func toTask(src serviceapi.Task) *pb.Task {
	out := new(pb.Task)
	out.Id = src.ID
	out.EntityId = src.EntityID
	out.EntityType = src.EntityType
	out.ResponsibleUserId = src.ResponsibleUserID
	out.Text = src.Text
	out.CompleteTill = src.CompleteTill
	out.TaskTypeId = src.TaskTypeID
	out.IsCompleted = src.IsCompleted
	out.ResultText = src.ResultText
	out.UpdatedAt = src.UpdatedAt
	return out
}
func fromTask(src *pb.Task) serviceapi.Task {
	var out serviceapi.Task
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.EntityID = src.EntityId
	out.EntityType = src.EntityType
	out.ResponsibleUserID = src.ResponsibleUserId
	out.Text = src.Text
	out.CompleteTill = src.CompleteTill
	out.TaskTypeID = src.TaskTypeId
	out.IsCompleted = src.IsCompleted
	out.ResultText = src.ResultText
	out.UpdatedAt = src.UpdatedAt
	return out
}
func toTaskPage(src serviceapi.TaskPage) *pb.TaskPage {
	out := new(pb.TaskPage)
	for _, item := range src.Tasks {
		out.Tasks = append(out.Tasks, toTask(item))
	}
	out.InvalidIds = append(out.InvalidIds, src.InvalidIDs...)
	return out
}
func fromTaskPage(src *pb.TaskPage) serviceapi.TaskPage {
	var out serviceapi.TaskPage
	if src == nil {
		return out
	}
	for _, item := range src.Tasks {
		out.Tasks = append(out.Tasks, fromTask(item))
	}
	out.InvalidIDs = append(out.InvalidIDs, src.InvalidIds...)
	return out
}
func toCatalogRequest(src serviceapi.CatalogRequest) *pb.CatalogRequest {
	out := new(pb.CatalogRequest)
	out.Auth = toAuth(src.Auth)
	return out
}
func fromCatalogRequest(src *pb.CatalogRequest) serviceapi.CatalogRequest {
	var out serviceapi.CatalogRequest
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	return out
}
func toPipelineStatus(src serviceapi.PipelineStatus) *pb.PipelineStatus {
	out := new(pb.PipelineStatus)
	out.Id = src.ID
	out.Name = src.Name
	return out
}
func fromPipelineStatus(src *pb.PipelineStatus) serviceapi.PipelineStatus {
	var out serviceapi.PipelineStatus
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.Name = src.Name
	return out
}
func toPipeline(src serviceapi.Pipeline) *pb.Pipeline {
	out := new(pb.Pipeline)
	out.Id = src.ID
	out.Name = src.Name
	for _, item := range src.Statuses {
		out.Statuses = append(out.Statuses, toPipelineStatus(item))
	}
	return out
}
func fromPipeline(src *pb.Pipeline) serviceapi.Pipeline {
	var out serviceapi.Pipeline
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.Name = src.Name
	for _, item := range src.Statuses {
		out.Statuses = append(out.Statuses, fromPipelineStatus(item))
	}
	return out
}
func toPipelineCatalog(src serviceapi.PipelineCatalog) *pb.PipelineCatalog {
	out := new(pb.PipelineCatalog)
	for _, item := range src.Pipelines {
		out.Pipelines = append(out.Pipelines, toPipeline(item))
	}
	out.FetchedAt = src.FetchedAt
	return out
}
func fromPipelineCatalog(src *pb.PipelineCatalog) serviceapi.PipelineCatalog {
	var out serviceapi.PipelineCatalog
	if src == nil {
		return out
	}
	for _, item := range src.Pipelines {
		out.Pipelines = append(out.Pipelines, fromPipeline(item))
	}
	out.FetchedAt = src.FetchedAt
	return out
}
func toCustomFieldsRequest(src serviceapi.CustomFieldsRequest) *pb.CustomFieldsRequest {
	out := new(pb.CustomFieldsRequest)
	out.Auth = toAuth(src.Auth)
	out.EntityType = src.EntityType
	return out
}
func fromCustomFieldsRequest(src *pb.CustomFieldsRequest) serviceapi.CustomFieldsRequest {
	var out serviceapi.CustomFieldsRequest
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.EntityType = src.EntityType
	return out
}
func toCustomFieldEnum(src serviceapi.CustomFieldEnum) *pb.CustomFieldEnum {
	out := new(pb.CustomFieldEnum)
	out.Id = src.ID
	out.Value = src.Value
	return out
}
func fromCustomFieldEnum(src *pb.CustomFieldEnum) serviceapi.CustomFieldEnum {
	var out serviceapi.CustomFieldEnum
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.Value = src.Value
	return out
}
func toCustomField(src serviceapi.CustomField) *pb.CustomField {
	out := new(pb.CustomField)
	out.Id = src.ID
	out.Name = src.Name
	out.Type = src.Type
	out.EntityType = src.EntityType
	for _, item := range src.Enums {
		out.Enums = append(out.Enums, toCustomFieldEnum(item))
	}
	return out
}
func fromCustomField(src *pb.CustomField) serviceapi.CustomField {
	var out serviceapi.CustomField
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.Name = src.Name
	out.Type = src.Type
	out.EntityType = src.EntityType
	for _, item := range src.Enums {
		out.Enums = append(out.Enums, fromCustomFieldEnum(item))
	}
	return out
}
func toCustomFieldCatalog(src serviceapi.CustomFieldCatalog) *pb.CustomFieldCatalog {
	out := new(pb.CustomFieldCatalog)
	for _, item := range src.Fields {
		out.Fields = append(out.Fields, toCustomField(item))
	}
	out.FetchedAt = src.FetchedAt
	return out
}
func fromCustomFieldCatalog(src *pb.CustomFieldCatalog) serviceapi.CustomFieldCatalog {
	var out serviceapi.CustomFieldCatalog
	if src == nil {
		return out
	}
	for _, item := range src.Fields {
		out.Fields = append(out.Fields, fromCustomField(item))
	}
	out.FetchedAt = src.FetchedAt
	return out
}
func toEntitiesRequest(src serviceapi.EntitiesRequest) *pb.EntitiesRequest {
	out := new(pb.EntitiesRequest)
	out.Auth = toAuth(src.Auth)
	out.EntityType = src.EntityType
	out.Ids = append(out.Ids, src.IDs...)
	return out
}
func fromEntitiesRequest(src *pb.EntitiesRequest) serviceapi.EntitiesRequest {
	var out serviceapi.EntitiesRequest
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.EntityType = src.EntityType
	out.IDs = append(out.IDs, src.Ids...)
	return out
}
func toEntityName(src serviceapi.EntityName) *pb.EntityName {
	out := new(pb.EntityName)
	out.Id = src.ID
	out.EntityType = src.EntityType
	out.Name = src.Name
	return out
}
func fromEntityName(src *pb.EntityName) serviceapi.EntityName {
	var out serviceapi.EntityName
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.EntityType = src.EntityType
	out.Name = src.Name
	return out
}
func toEntityCatalog(src serviceapi.EntityCatalog) *pb.EntityCatalog {
	out := new(pb.EntityCatalog)
	for _, item := range src.Entities {
		out.Entities = append(out.Entities, toEntityName(item))
	}
	out.InvalidIds = append(out.InvalidIds, src.InvalidIDs...)
	return out
}
func fromEntityCatalog(src *pb.EntityCatalog) serviceapi.EntityCatalog {
	var out serviceapi.EntityCatalog
	if src == nil {
		return out
	}
	for _, item := range src.Entities {
		out.Entities = append(out.Entities, fromEntityName(item))
	}
	out.InvalidIDs = append(out.InvalidIDs, src.InvalidIds...)
	return out
}
func toEventRequest(src serviceapi.EventRequest) *pb.EventRequest {
	out := new(pb.EventRequest)
	out.Auth = toAuth(src.Auth)
	out.EventId = src.EventID
	return out
}
func fromEventRequest(src *pb.EventRequest) serviceapi.EventRequest {
	var out serviceapi.EventRequest
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.EventID = src.EventId
	return out
}
func toEventPageRequest(src serviceapi.EventPageRequest) *pb.EventPageRequest {
	out := new(pb.EventPageRequest)
	out.Auth = toAuth(src.Auth)
	out.From = src.From
	out.To = src.To
	out.Page = boundedInt32(src.Page)
	out.Limit = boundedInt32(src.Limit)
	return out
}
func fromEventPageRequest(src *pb.EventPageRequest) serviceapi.EventPageRequest {
	var out serviceapi.EventPageRequest
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.From = src.From
	out.To = src.To
	out.Page = int(src.Page)
	out.Limit = int(src.Limit)
	return out
}
func toEventPage(src serviceapi.EventPage) *pb.EventPage {
	out := new(pb.EventPage)
	for _, item := range src.Events {
		out.Events = append(out.Events, toEvent(item))
	}
	out.HasNext = src.HasNext
	return out
}
func fromEventPage(src *pb.EventPage) serviceapi.EventPage {
	var out serviceapi.EventPage
	if src == nil {
		return out
	}
	for _, item := range src.Events {
		out.Events = append(out.Events, fromEvent(item))
	}
	out.HasNext = src.HasNext
	return out
}
func toUser(src serviceapi.User) *pb.User {
	out := new(pb.User)
	out.Id = src.ID
	out.Name = src.Name
	out.GroupId = src.GroupID
	out.GroupName = src.GroupName
	return out
}
func fromUser(src *pb.User) serviceapi.User {
	var out serviceapi.User
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.Name = src.Name
	out.GroupID = src.GroupId
	out.GroupName = src.GroupName
	return out
}
func toUsersRequest(src serviceapi.UsersRequest) *pb.UsersRequest {
	out := new(pb.UsersRequest)
	out.Auth = toAuth(src.Auth)
	out.UserIds = append(out.UserIds, src.UserIDs...)
	return out
}
func fromUsersRequest(src *pb.UsersRequest) serviceapi.UsersRequest {
	var out serviceapi.UsersRequest
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.UserIDs = append(out.UserIDs, src.UserIds...)
	return out
}
func toDirectory(src serviceapi.Directory) *pb.Directory {
	out := new(pb.Directory)
	for _, item := range src.Users {
		out.Users = append(out.Users, toUser(item))
	}
	out.Timezone = src.Timezone
	return out
}
func fromDirectory(src *pb.Directory) serviceapi.Directory {
	var out serviceapi.Directory
	if src == nil {
		return out
	}
	for _, item := range src.Users {
		out.Users = append(out.Users, fromUser(item))
	}
	out.Timezone = src.Timezone
	return out
}
func toQuery(src serviceapi.Query) *pb.Query {
	out := new(pb.Query)
	out.Auth = toAuth(src.Auth)
	out.From = src.From
	out.To = src.To
	out.UserIds = append(out.UserIds, src.UserIDs...)
	out.Limit = boundedInt32(src.Limit)
	out.Cursor = src.Cursor
	out.Types = append(out.Types, src.Types...)
	out.TypePrefix = src.TypePrefix
	out.EntityType = src.EntityType
	out.EntityIds = append(out.EntityIds, src.EntityIDs...)
	out.Order = src.Order
	out.Compact = src.Compact
	out.Categories = append(out.Categories, src.Categories...)
	out.IncludeUnknownAuthors = src.IncludeUnknownAuthors
	out.Timezone = src.Timezone
	out.Buckets = src.Buckets
	out.DirectoryUserIds = append(out.DirectoryUserIds, src.DirectoryUserIDs...)
	out.GroupId = src.GroupID
	return out
}
func fromQuery(src *pb.Query) serviceapi.Query {
	var out serviceapi.Query
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.From = src.From
	out.To = src.To
	out.UserIDs = append(out.UserIDs, src.UserIds...)
	out.Limit = int(src.Limit)
	out.Cursor = src.Cursor
	out.Types = append(out.Types, src.Types...)
	out.TypePrefix = src.TypePrefix
	out.EntityType = src.EntityType
	out.EntityIDs = append(out.EntityIDs, src.EntityIds...)
	out.Order = src.Order
	out.Compact = src.Compact
	out.Categories = append(out.Categories, src.Categories...)
	out.IncludeUnknownAuthors = src.IncludeUnknownAuthors
	out.Timezone = src.Timezone
	out.Buckets = src.Buckets
	out.DirectoryUserIDs = append(out.DirectoryUserIDs, src.DirectoryUserIds...)
	out.GroupID = src.GroupId
	return out
}
func toUserSummary(src serviceapi.UserSummary) *pb.UserSummary {
	out := new(pb.UserSummary)
	out.UserId = src.UserID
	out.UniqueEvents = src.UniqueEvents
	out.LastEventAt = src.LastEventAt
	out.FirstEventAt = src.FirstEventAt
	out.EntityCount = src.EntityCount
	out.TaskCompletedEvents = src.TaskCompletedEvents
	out.UniqueCompletedTasks = src.UniqueCompletedTasks
	for _, item := range src.CategoryCounts {
		out.CategoryCounts = append(out.CategoryCounts, toCategoryCount(item))
	}
	return out
}
func fromUserSummary(src *pb.UserSummary) serviceapi.UserSummary {
	var out serviceapi.UserSummary
	if src == nil {
		return out
	}
	out.UserID = src.UserId
	out.UniqueEvents = src.UniqueEvents
	out.LastEventAt = src.LastEventAt
	out.FirstEventAt = src.FirstEventAt
	out.EntityCount = src.EntityCount
	out.TaskCompletedEvents = src.TaskCompletedEvents
	out.UniqueCompletedTasks = src.UniqueCompletedTasks
	for _, item := range src.CategoryCounts {
		out.CategoryCounts = append(out.CategoryCounts, fromCategoryCount(item))
	}
	return out
}
func toSyncStatus(src serviceapi.SyncStatus) *pb.SyncStatus {
	out := new(pb.SyncStatus)
	out.Enabled = src.Enabled
	out.State = src.State
	out.HistoryFrom = src.HistoryFrom
	out.VerifiedFrom = src.VerifiedFrom
	out.VerifiedThrough = src.VerifiedThrough
	out.WindowFrom = src.WindowFrom
	out.WindowTo = src.WindowTo
	out.NextPage = boundedInt32(src.NextPage)
	out.LastSuccessAt = src.LastSuccessAt
	out.LastEventAt = src.LastEventAt
	out.LagSeconds = src.LagSeconds
	out.ErrorCode = src.ErrorCode
	out.ReauthRequired = src.ReauthRequired
	out.Verification = src.Verification
	return out
}
func fromSyncStatus(src *pb.SyncStatus) serviceapi.SyncStatus {
	var out serviceapi.SyncStatus
	if src == nil {
		return out
	}
	out.Enabled = src.Enabled
	out.State = src.State
	out.HistoryFrom = src.HistoryFrom
	out.VerifiedFrom = src.VerifiedFrom
	out.VerifiedThrough = src.VerifiedThrough
	out.WindowFrom = src.WindowFrom
	out.WindowTo = src.WindowTo
	out.NextPage = int(src.NextPage)
	out.LastSuccessAt = src.LastSuccessAt
	out.LastEventAt = src.LastEventAt
	out.LagSeconds = src.LagSeconds
	out.ErrorCode = src.ErrorCode
	out.ReauthRequired = src.ReauthRequired
	out.Verification = src.Verification
	return out
}
func toQueryResult(src serviceapi.QueryResult) *pb.QueryResult {
	out := new(pb.QueryResult)
	for _, item := range src.Events {
		out.Events = append(out.Events, toEvent(item))
	}
	for _, item := range src.Summaries {
		out.Summaries = append(out.Summaries, toUserSummary(item))
	}
	out.NextCursor = src.NextCursor
	out.Status = toSyncStatus(src.Status)
	out.ReadVersion = boundedInt32(src.ReadVersion)
	out.PayloadsOmitted = src.PayloadsOmitted
	out.Totals = toQueryTotals(src.Totals)
	for _, item := range src.Timeline {
		out.Timeline = append(out.Timeline, toTimeBucket(item))
	}
	return out
}
func fromQueryResult(src *pb.QueryResult) serviceapi.QueryResult {
	var out serviceapi.QueryResult
	if src == nil {
		return out
	}
	for _, item := range src.Events {
		out.Events = append(out.Events, fromEvent(item))
	}
	for _, item := range src.Summaries {
		out.Summaries = append(out.Summaries, fromUserSummary(item))
	}
	out.NextCursor = src.NextCursor
	out.Status = fromSyncStatus(src.Status)
	out.ReadVersion = int(src.ReadVersion)
	out.PayloadsOmitted = src.PayloadsOmitted
	out.Totals = fromQueryTotals(src.Totals)
	for _, item := range src.Timeline {
		out.Timeline = append(out.Timeline, fromTimeBucket(item))
	}
	return out
}
func toCommand(src serviceapi.Command) *pb.Command {
	out := new(pb.Command)
	out.Auth = toAuth(src.Auth)
	out.CommandId = src.CommandID
	out.Kind = src.Kind
	out.From = src.From
	out.To = src.To
	out.InitialDays = boundedInt32(src.InitialDays)
	out.RetentionDays = boundedInt32(src.RetentionDays)
	return out
}
func fromCommand(src *pb.Command) serviceapi.Command {
	var out serviceapi.Command
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.CommandID = src.CommandId
	out.Kind = src.Kind
	out.From = src.From
	out.To = src.To
	out.InitialDays = int(src.InitialDays)
	out.RetentionDays = int(src.RetentionDays)
	return out
}
func toOperation(src serviceapi.Operation) *pb.Operation {
	out := new(pb.Operation)
	out.Id = src.ID
	out.CommandId = src.CommandID
	out.State = src.State
	out.ErrorCode = src.ErrorCode
	out.Processed = src.Processed
	out.Inserted = src.Inserted
	out.Updated = src.Updated
	out.Deduplicated = src.Deduplicated
	return out
}
func fromOperation(src *pb.Operation) serviceapi.Operation {
	var out serviceapi.Operation
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.CommandID = src.CommandId
	out.State = src.State
	out.ErrorCode = src.ErrorCode
	out.Processed = src.Processed
	out.Inserted = src.Inserted
	out.Updated = src.Updated
	out.Deduplicated = src.Deduplicated
	return out
}
func toOperationRequest(src serviceapi.OperationRequest) *pb.OperationRequest {
	out := new(pb.OperationRequest)
	out.Auth = toAuth(src.Auth)
	out.OperationId = src.OperationID
	return out
}
func fromOperationRequest(src *pb.OperationRequest) serviceapi.OperationRequest {
	var out serviceapi.OperationRequest
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.OperationID = src.OperationId
	return out
}
func toSettings(src serviceapi.Settings) *pb.Settings {
	out := new(pb.Settings)
	out.InitialDays = boundedInt32(src.InitialDays)
	out.RetentionDays = boundedInt32(src.RetentionDays)
	return out
}
func fromSettings(src *pb.Settings) serviceapi.Settings {
	var out serviceapi.Settings
	if src == nil {
		return out
	}
	out.InitialDays = int(src.InitialDays)
	out.RetentionDays = int(src.RetentionDays)
	return out
}
func toSettingsCommand(src serviceapi.SettingsCommand) *pb.SettingsCommand {
	out := new(pb.SettingsCommand)
	out.Auth = toAuth(src.Auth)
	out.CommandId = src.CommandID
	out.Settings = toSettings(src.Settings)
	return out
}
func fromSettingsCommand(src *pb.SettingsCommand) serviceapi.SettingsCommand {
	var out serviceapi.SettingsCommand
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.CommandID = src.CommandId
	out.Settings = fromSettings(src.Settings)
	return out
}
func toPanel(src serviceapi.Panel) *pb.Panel {
	out := new(pb.Panel)
	for _, item := range src.Users {
		out.Users = append(out.Users, toUser(item))
	}
	out.Timezone = src.Timezone
	out.Data = toQueryResult(src.Data)
	out.Settings = toSettings(src.Settings)
	out.Coverage = src.Coverage
	out.Freshness = src.Freshness
	out.EmptyReason = src.EmptyReason
	out.InterpretationVersion = boundedInt32(src.InterpretationVersion)
	return out
}
func fromPanel(src *pb.Panel) serviceapi.Panel {
	var out serviceapi.Panel
	if src == nil {
		return out
	}
	for _, item := range src.Users {
		out.Users = append(out.Users, fromUser(item))
	}
	out.Timezone = src.Timezone
	out.Data = fromQueryResult(src.Data)
	out.Settings = fromSettings(src.Settings)
	out.Coverage = src.Coverage
	out.Freshness = src.Freshness
	out.EmptyReason = src.EmptyReason
	out.InterpretationVersion = int(src.InterpretationVersion)
	return out
}
func toDisplayWindow(src serviceapi.DisplayWindow) *pb.DisplayWindow {
	out := new(pb.DisplayWindow)
	out.From = src.From
	out.To = src.To
	return out
}
func fromDisplayWindow(src *pb.DisplayWindow) serviceapi.DisplayWindow {
	var out serviceapi.DisplayWindow
	if src == nil {
		return out
	}
	out.From = src.From
	out.To = src.To
	return out
}
func toShareLookupRequest(src serviceapi.ShareLookupRequest) *pb.ShareLookupRequest {
	out := new(pb.ShareLookupRequest)
	out.ViewKey = src.ViewKey
	return out
}
func fromShareLookupRequest(src *pb.ShareLookupRequest) serviceapi.ShareLookupRequest {
	var out serviceapi.ShareLookupRequest
	if src == nil {
		return out
	}
	out.ViewKey = src.ViewKey
	return out
}
func toShareLookup(src serviceapi.ShareLookup) *pb.ShareLookup {
	out := new(pb.ShareLookup)
	out.IntegrationId = src.IntegrationID.String()
	out.InstallationId = src.InstallationID.String()
	out.PanelId = src.PanelID.String()
	out.Enabled = src.Enabled
	out.ViewKeyVersion = boundedInt32(src.ViewKeyVersion)
	out.EmployeeIds = append(out.EmployeeIds, src.EmployeeIDs...)
	return out
}
func fromShareLookup(src *pb.ShareLookup) serviceapi.ShareLookup {
	var out serviceapi.ShareLookup
	if src == nil {
		return out
	}
	out.IntegrationID = parseUUID(src.IntegrationId)
	out.InstallationID = parseUUID(src.InstallationId)
	out.PanelID = parseUUID(src.PanelId)
	out.Enabled = src.Enabled
	out.ViewKeyVersion = int(src.ViewKeyVersion)
	out.EmployeeIDs = append(out.EmployeeIDs, src.EmployeeIds...)
	return out
}
func toPanelRef(src serviceapi.PanelRef) *pb.PanelRef {
	out := new(pb.PanelRef)
	out.Auth = toAuth(src.Auth)
	out.PanelId = src.PanelID.String()
	return out
}
func fromPanelRef(src *pb.PanelRef) serviceapi.PanelRef {
	var out serviceapi.PanelRef
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.PanelID = parseUUID(src.PanelId)
	return out
}
func toPanelCommand(src serviceapi.PanelCommand) *pb.PanelCommand {
	out := new(pb.PanelCommand)
	out.Auth = toAuth(src.Auth)
	out.CommandId = src.CommandID
	out.PanelId = src.PanelID.String()
	out.Name = src.Name
	out.EmployeeIds = append(out.EmployeeIds, src.EmployeeIDs...)
	out.DisplayWindow = toDisplayWindow(src.DisplayWindow)
	out.Enabled = src.Enabled
	out.Revision = src.Revision
	out.HasName = src.HasName
	out.HasEmployees = src.HasEmployees
	out.HasWindow = src.HasWindow
	return out
}
func fromPanelCommand(src *pb.PanelCommand) serviceapi.PanelCommand {
	var out serviceapi.PanelCommand
	if src == nil {
		return out
	}
	out.Auth = fromAuth(src.Auth)
	out.CommandID = src.CommandId
	out.PanelID = parseUUID(src.PanelId)
	out.Name = src.Name
	out.EmployeeIDs = append(out.EmployeeIDs, src.EmployeeIds...)
	out.DisplayWindow = fromDisplayWindow(src.DisplayWindow)
	out.Enabled = src.Enabled
	out.Revision = src.Revision
	out.HasName = src.HasName
	out.HasEmployees = src.HasEmployees
	out.HasWindow = src.HasWindow
	return out
}
func toManagedPanel(src serviceapi.ManagedPanel) *pb.ManagedPanel {
	out := new(pb.ManagedPanel)
	out.Id = src.ID.String()
	out.Name = src.Name
	out.EmployeeIds = append(out.EmployeeIds, src.EmployeeIDs...)
	out.DisplayWindow = toDisplayWindow(src.DisplayWindow)
	out.Timezone = src.Timezone
	out.Enabled = src.Enabled
	out.Revision = src.Revision
	out.UpdatedAt = src.UpdatedAt.Format(time.RFC3339Nano)
	out.ShareUrlIssued = src.ShareUrlIssued
	out.ViewKey = src.ViewKey
	out.ShareUrl = src.ShareUrl
	out.ViewKeyVersion = boundedInt32(src.ViewKeyVersion)
	return out
}
func fromManagedPanel(src *pb.ManagedPanel) serviceapi.ManagedPanel {
	var out serviceapi.ManagedPanel
	if src == nil {
		return out
	}
	out.ID = parseUUID(src.Id)
	out.Name = src.Name
	out.EmployeeIDs = append(out.EmployeeIDs, src.EmployeeIds...)
	out.DisplayWindow = fromDisplayWindow(src.DisplayWindow)
	out.Timezone = src.Timezone
	out.Enabled = src.Enabled
	out.Revision = src.Revision
	out.UpdatedAt = parseTime(src.UpdatedAt)
	out.ShareUrlIssued = src.ShareUrlIssued
	out.ViewKey = src.ViewKey
	out.ShareUrl = src.ShareUrl
	out.ViewKeyVersion = int(src.ViewKeyVersion)
	return out
}
func toManagedPanelPage(src serviceapi.ManagedPanelPage) *pb.ManagedPanelPage {
	out := new(pb.ManagedPanelPage)
	for _, item := range src.Panels {
		out.Panels = append(out.Panels, toManagedPanel(item))
	}
	return out
}
func fromManagedPanelPage(src *pb.ManagedPanelPage) serviceapi.ManagedPanelPage {
	var out serviceapi.ManagedPanelPage
	if src == nil {
		return out
	}
	for _, item := range src.Panels {
		out.Panels = append(out.Panels, fromManagedPanel(item))
	}
	return out
}
func toViewerPanel(src serviceapi.ViewerPanel) *pb.ViewerPanel {
	out := new(pb.ViewerPanel)
	out.Name = src.Name
	out.Timezone = src.Timezone
	out.DisplayWindow = toDisplayWindow(src.DisplayWindow)
	for _, item := range src.Employees {
		out.Employees = append(out.Employees, toUser(item))
	}
	out.InterpretationVersion = boundedInt32(src.InterpretationVersion)
	return out
}
func fromViewerPanel(src *pb.ViewerPanel) serviceapi.ViewerPanel {
	var out serviceapi.ViewerPanel
	if src == nil {
		return out
	}
	out.Name = src.Name
	out.Timezone = src.Timezone
	out.DisplayWindow = fromDisplayWindow(src.DisplayWindow)
	for _, item := range src.Employees {
		out.Employees = append(out.Employees, fromUser(item))
	}
	out.InterpretationVersion = int(src.InterpretationVersion)
	return out
}
func toViewerTimeline(src serviceapi.ViewerTimeline) *pb.ViewerTimeline {
	out := new(pb.ViewerTimeline)
	for _, item := range src.Employees {
		out.Employees = append(out.Employees, toUser(item))
	}
	out.Timezone = src.Timezone
	out.Data = toQueryResult(src.Data)
	out.Coverage = src.Coverage
	out.Freshness = src.Freshness
	out.EmptyReason = src.EmptyReason
	out.InterpretationVersion = boundedInt32(src.InterpretationVersion)
	return out
}
func fromViewerTimeline(src *pb.ViewerTimeline) serviceapi.ViewerTimeline {
	var out serviceapi.ViewerTimeline
	if src == nil {
		return out
	}
	for _, item := range src.Employees {
		out.Employees = append(out.Employees, fromUser(item))
	}
	out.Timezone = src.Timezone
	out.Data = fromQueryResult(src.Data)
	out.Coverage = src.Coverage
	out.Freshness = src.Freshness
	out.EmptyReason = src.EmptyReason
	out.InterpretationVersion = int(src.InterpretationVersion)
	return out
}
func toViewerEmployee(src serviceapi.ViewerEmployee) *pb.ViewerEmployee {
	out := new(pb.ViewerEmployee)
	out.Employee = toUser(src.Employee)
	out.Timezone = src.Timezone
	out.Data = toQueryResult(src.Data)
	out.Coverage = src.Coverage
	out.Freshness = src.Freshness
	out.EmptyReason = src.EmptyReason
	out.InterpretationVersion = boundedInt32(src.InterpretationVersion)
	return out
}
func fromViewerEmployee(src *pb.ViewerEmployee) serviceapi.ViewerEmployee {
	var out serviceapi.ViewerEmployee
	if src == nil {
		return out
	}
	out.Employee = fromUser(src.Employee)
	out.Timezone = src.Timezone
	out.Data = fromQueryResult(src.Data)
	out.Coverage = src.Coverage
	out.Freshness = src.Freshness
	out.EmptyReason = src.EmptyReason
	out.InterpretationVersion = int(src.InterpretationVersion)
	return out
}
func toBootstrapAccountRequest(src serviceapi.BootstrapAccountRequest) *pb.BootstrapAccountRequest {
	out := new(pb.BootstrapAccountRequest)
	out.IntegrationId = src.IntegrationID.String()
	out.AccountDomain = src.AccountDomain
	out.AccessToken = src.AccessToken
	return out
}
func fromBootstrapAccountRequest(src *pb.BootstrapAccountRequest) serviceapi.BootstrapAccountRequest {
	var out serviceapi.BootstrapAccountRequest
	if src == nil {
		return out
	}
	out.IntegrationID = parseUUID(src.IntegrationId)
	out.AccountDomain = src.AccountDomain
	out.AccessToken = src.AccessToken
	return out
}
func toBootstrapAccount(src serviceapi.BootstrapAccount) *pb.BootstrapAccount {
	out := new(pb.BootstrapAccount)
	out.Id = src.ID
	out.Subdomain = src.Subdomain
	return out
}
func fromBootstrapAccount(src *pb.BootstrapAccount) serviceapi.BootstrapAccount {
	var out serviceapi.BootstrapAccount
	if src == nil {
		return out
	}
	out.ID = src.Id
	out.Subdomain = src.Subdomain
	return out
}
