// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.31.1
// source: api/proto/services.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// v1 is additive. Never reuse field numbers. All ranges are Unix seconds.
// All requests carry a short-lived Core Ed25519 delegation, transported with
// authenticated mTLS service identity. Maximum message size is 4 MiB.
type Auth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Auth) Reset() {
	*x = Auth{}
	mi := &file_api_proto_services_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Auth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Auth) ProtoMessage() {}

func (x *Auth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Auth.ProtoReflect.Descriptor instead.
func (*Auth) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{0}
}

func (x *Auth) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type Grant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Audience      string                 `protobuf:"bytes,1,opt,name=audience,proto3" json:"audience,omitempty"`
	Action        string                 `protobuf:"bytes,2,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grant) Reset() {
	*x = Grant{}
	mi := &file_api_proto_services_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grant) ProtoMessage() {}

func (x *Grant) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grant.ProtoReflect.Descriptor instead.
func (*Grant) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{1}
}

func (x *Grant) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *Grant) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type IssueRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IntegrationId  string                 `protobuf:"bytes,1,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
	InstallationId string                 `protobuf:"bytes,2,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	ActorId        int64                  `protobuf:"varint,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	System         bool                   `protobuf:"varint,4,opt,name=system,proto3" json:"system,omitempty"`
	Consumer       string                 `protobuf:"bytes,5,opt,name=consumer,proto3" json:"consumer,omitempty"`
	RequestId      string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	Grants         []*Grant               `protobuf:"bytes,7,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IssueRequest) Reset() {
	*x = IssueRequest{}
	mi := &file_api_proto_services_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueRequest) ProtoMessage() {}

func (x *IssueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueRequest.ProtoReflect.Descriptor instead.
func (*IssueRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{2}
}

func (x *IssueRequest) GetIntegrationId() string {
	if x != nil {
		return x.IntegrationId
	}
	return ""
}

func (x *IssueRequest) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *IssueRequest) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *IssueRequest) GetSystem() bool {
	if x != nil {
		return x.System
	}
	return false
}

func (x *IssueRequest) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *IssueRequest) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *IssueRequest) GetGrants() []*Grant {
	if x != nil {
		return x.Grants
	}
	return nil
}

type ValidateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	Audience      string                 `protobuf:"bytes,2,opt,name=audience,proto3" json:"audience,omitempty"`
	Action        string                 `protobuf:"bytes,3,opt,name=action,proto3" json:"action,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateRequest) Reset() {
	*x = ValidateRequest{}
	mi := &file_api_proto_services_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateRequest) ProtoMessage() {}

func (x *ValidateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateRequest.ProtoReflect.Descriptor instead.
func (*ValidateRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{3}
}

func (x *ValidateRequest) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *ValidateRequest) GetAudience() string {
	if x != nil {
		return x.Audience
	}
	return ""
}

func (x *ValidateRequest) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

type Principal struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	IntegrationId  string                 `protobuf:"bytes,1,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
	InstallationId string                 `protobuf:"bytes,2,opt,name=installation_id,json=installationId,proto3" json:"installation_id,omitempty"`
	ActorId        int64                  `protobuf:"varint,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	System         bool                   `protobuf:"varint,4,opt,name=system,proto3" json:"system,omitempty"`
	Consumer       string                 `protobuf:"bytes,5,opt,name=consumer,proto3" json:"consumer,omitempty"`
	RequestId      string                 `protobuf:"bytes,6,opt,name=request_id,json=requestId,proto3" json:"request_id,omitempty"`
	ExpiresAt      string                 `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_api_proto_services_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{4}
}

func (x *Principal) GetIntegrationId() string {
	if x != nil {
		return x.IntegrationId
	}
	return ""
}

func (x *Principal) GetInstallationId() string {
	if x != nil {
		return x.InstallationId
	}
	return ""
}

func (x *Principal) GetActorId() int64 {
	if x != nil {
		return x.ActorId
	}
	return 0
}

func (x *Principal) GetSystem() bool {
	if x != nil {
		return x.System
	}
	return false
}

func (x *Principal) GetConsumer() string {
	if x != nil {
		return x.Consumer
	}
	return ""
}

func (x *Principal) GetRequestId() string {
	if x != nil {
		return x.RequestId
	}
	return ""
}

func (x *Principal) GetExpiresAt() string {
	if x != nil {
		return x.ExpiresAt
	}
	return ""
}

type Event struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CreatedAt     int64                  `protobuf:"varint,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     int64                  `protobuf:"varint,3,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Type          string                 `protobuf:"bytes,4,opt,name=type,proto3" json:"type,omitempty"`
	EntityId      int64                  `protobuf:"varint,5,opt,name=entity_id,json=entityId,proto3" json:"entity_id,omitempty"`
	EntityType    string                 `protobuf:"bytes,6,opt,name=entity_type,json=entityType,proto3" json:"entity_type,omitempty"`
	ValueBefore   []byte                 `protobuf:"bytes,7,opt,name=value_before,json=valueBefore,proto3" json:"value_before,omitempty"`
	ValueAfter    []byte                 `protobuf:"bytes,8,opt,name=value_after,json=valueAfter,proto3" json:"value_after,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Event) Reset() {
	*x = Event{}
	mi := &file_api_proto_services_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Event) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Event) ProtoMessage() {}

func (x *Event) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Event.ProtoReflect.Descriptor instead.
func (*Event) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{5}
}

func (x *Event) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Event) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

func (x *Event) GetCreatedBy() int64 {
	if x != nil {
		return x.CreatedBy
	}
	return 0
}

func (x *Event) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Event) GetEntityId() int64 {
	if x != nil {
		return x.EntityId
	}
	return 0
}

func (x *Event) GetEntityType() string {
	if x != nil {
		return x.EntityType
	}
	return ""
}

func (x *Event) GetValueBefore() []byte {
	if x != nil {
		return x.ValueBefore
	}
	return nil
}

func (x *Event) GetValueAfter() []byte {
	if x != nil {
		return x.ValueAfter
	}
	return nil
}

type EventPageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	From          int64                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	Page          int32                  `protobuf:"varint,4,opt,name=page,proto3" json:"page,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPageRequest) Reset() {
	*x = EventPageRequest{}
	mi := &file_api_proto_services_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPageRequest) ProtoMessage() {}

func (x *EventPageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPageRequest.ProtoReflect.Descriptor instead.
func (*EventPageRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{6}
}

func (x *EventPageRequest) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *EventPageRequest) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *EventPageRequest) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *EventPageRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *EventPageRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type EventPage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	HasNext       bool                   `protobuf:"varint,2,opt,name=has_next,json=hasNext,proto3" json:"has_next,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EventPage) Reset() {
	*x = EventPage{}
	mi := &file_api_proto_services_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EventPage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EventPage) ProtoMessage() {}

func (x *EventPage) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EventPage.ProtoReflect.Descriptor instead.
func (*EventPage) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{7}
}

func (x *EventPage) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *EventPage) GetHasNext() bool {
	if x != nil {
		return x.HasNext
	}
	return false
}

type User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	GroupId       int64                  `protobuf:"varint,3,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	GroupName     string                 `protobuf:"bytes,4,opt,name=group_name,json=groupName,proto3" json:"group_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *User) Reset() {
	*x = User{}
	mi := &file_api_proto_services_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*User) ProtoMessage() {}

func (x *User) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use User.ProtoReflect.Descriptor instead.
func (*User) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{8}
}

func (x *User) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *User) GetGroupId() int64 {
	if x != nil {
		return x.GroupId
	}
	return 0
}

func (x *User) GetGroupName() string {
	if x != nil {
		return x.GroupName
	}
	return ""
}

type UsersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	UserIds       []int64                `protobuf:"varint,2,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UsersRequest) Reset() {
	*x = UsersRequest{}
	mi := &file_api_proto_services_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UsersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UsersRequest) ProtoMessage() {}

func (x *UsersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UsersRequest.ProtoReflect.Descriptor instead.
func (*UsersRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{9}
}

func (x *UsersRequest) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *UsersRequest) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

type Directory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Directory) Reset() {
	*x = Directory{}
	mi := &file_api_proto_services_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Directory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Directory) ProtoMessage() {}

func (x *Directory) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Directory.ProtoReflect.Descriptor instead.
func (*Directory) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{10}
}

func (x *Directory) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Directory) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

type Query struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	From          int64                  `protobuf:"varint,2,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,3,opt,name=to,proto3" json:"to,omitempty"`
	UserIds       []int64                `protobuf:"varint,4,rep,packed,name=user_ids,json=userIds,proto3" json:"user_ids,omitempty"`
	Limit         int32                  `protobuf:"varint,5,opt,name=limit,proto3" json:"limit,omitempty"`
	Cursor        string                 `protobuf:"bytes,6,opt,name=cursor,proto3" json:"cursor,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Query) Reset() {
	*x = Query{}
	mi := &file_api_proto_services_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Query) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Query) ProtoMessage() {}

func (x *Query) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Query.ProtoReflect.Descriptor instead.
func (*Query) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{11}
}

func (x *Query) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Query) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Query) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Query) GetUserIds() []int64 {
	if x != nil {
		return x.UserIds
	}
	return nil
}

func (x *Query) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Query) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

type UserSummary struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UniqueEvents  int64                  `protobuf:"varint,2,opt,name=unique_events,json=uniqueEvents,proto3" json:"unique_events,omitempty"`
	LastEventAt   int64                  `protobuf:"varint,3,opt,name=last_event_at,json=lastEventAt,proto3" json:"last_event_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSummary) Reset() {
	*x = UserSummary{}
	mi := &file_api_proto_services_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSummary) ProtoMessage() {}

func (x *UserSummary) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSummary.ProtoReflect.Descriptor instead.
func (*UserSummary) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{12}
}

func (x *UserSummary) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserSummary) GetUniqueEvents() int64 {
	if x != nil {
		return x.UniqueEvents
	}
	return 0
}

func (x *UserSummary) GetLastEventAt() int64 {
	if x != nil {
		return x.LastEventAt
	}
	return 0
}

type SyncStatus struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Enabled         bool                   `protobuf:"varint,1,opt,name=enabled,proto3" json:"enabled,omitempty"`
	State           string                 `protobuf:"bytes,2,opt,name=state,proto3" json:"state,omitempty"`
	HistoryFrom     int64                  `protobuf:"varint,3,opt,name=history_from,json=historyFrom,proto3" json:"history_from,omitempty"`
	VerifiedFrom    int64                  `protobuf:"varint,4,opt,name=verified_from,json=verifiedFrom,proto3" json:"verified_from,omitempty"`
	VerifiedThrough int64                  `protobuf:"varint,5,opt,name=verified_through,json=verifiedThrough,proto3" json:"verified_through,omitempty"`
	WindowFrom      int64                  `protobuf:"varint,6,opt,name=window_from,json=windowFrom,proto3" json:"window_from,omitempty"`
	WindowTo        int64                  `protobuf:"varint,7,opt,name=window_to,json=windowTo,proto3" json:"window_to,omitempty"`
	NextPage        int32                  `protobuf:"varint,8,opt,name=next_page,json=nextPage,proto3" json:"next_page,omitempty"`
	LastSuccessAt   int64                  `protobuf:"varint,9,opt,name=last_success_at,json=lastSuccessAt,proto3" json:"last_success_at,omitempty"`
	LastEventAt     int64                  `protobuf:"varint,10,opt,name=last_event_at,json=lastEventAt,proto3" json:"last_event_at,omitempty"`
	LagSeconds      int64                  `protobuf:"varint,11,opt,name=lag_seconds,json=lagSeconds,proto3" json:"lag_seconds,omitempty"`
	ErrorCode       string                 `protobuf:"bytes,12,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	ReauthRequired  bool                   `protobuf:"varint,13,opt,name=reauth_required,json=reauthRequired,proto3" json:"reauth_required,omitempty"`
	Verification    string                 `protobuf:"bytes,14,opt,name=verification,proto3" json:"verification,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *SyncStatus) Reset() {
	*x = SyncStatus{}
	mi := &file_api_proto_services_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncStatus) ProtoMessage() {}

func (x *SyncStatus) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncStatus.ProtoReflect.Descriptor instead.
func (*SyncStatus) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{13}
}

func (x *SyncStatus) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *SyncStatus) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *SyncStatus) GetHistoryFrom() int64 {
	if x != nil {
		return x.HistoryFrom
	}
	return 0
}

func (x *SyncStatus) GetVerifiedFrom() int64 {
	if x != nil {
		return x.VerifiedFrom
	}
	return 0
}

func (x *SyncStatus) GetVerifiedThrough() int64 {
	if x != nil {
		return x.VerifiedThrough
	}
	return 0
}

func (x *SyncStatus) GetWindowFrom() int64 {
	if x != nil {
		return x.WindowFrom
	}
	return 0
}

func (x *SyncStatus) GetWindowTo() int64 {
	if x != nil {
		return x.WindowTo
	}
	return 0
}

func (x *SyncStatus) GetNextPage() int32 {
	if x != nil {
		return x.NextPage
	}
	return 0
}

func (x *SyncStatus) GetLastSuccessAt() int64 {
	if x != nil {
		return x.LastSuccessAt
	}
	return 0
}

func (x *SyncStatus) GetLastEventAt() int64 {
	if x != nil {
		return x.LastEventAt
	}
	return 0
}

func (x *SyncStatus) GetLagSeconds() int64 {
	if x != nil {
		return x.LagSeconds
	}
	return 0
}

func (x *SyncStatus) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *SyncStatus) GetReauthRequired() bool {
	if x != nil {
		return x.ReauthRequired
	}
	return false
}

func (x *SyncStatus) GetVerification() string {
	if x != nil {
		return x.Verification
	}
	return ""
}

type QueryResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Events        []*Event               `protobuf:"bytes,1,rep,name=events,proto3" json:"events,omitempty"`
	Summaries     []*UserSummary         `protobuf:"bytes,2,rep,name=summaries,proto3" json:"summaries,omitempty"`
	NextCursor    string                 `protobuf:"bytes,3,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	Status        *SyncStatus            `protobuf:"bytes,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResult) Reset() {
	*x = QueryResult{}
	mi := &file_api_proto_services_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResult) ProtoMessage() {}

func (x *QueryResult) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResult.ProtoReflect.Descriptor instead.
func (*QueryResult) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{14}
}

func (x *QueryResult) GetEvents() []*Event {
	if x != nil {
		return x.Events
	}
	return nil
}

func (x *QueryResult) GetSummaries() []*UserSummary {
	if x != nil {
		return x.Summaries
	}
	return nil
}

func (x *QueryResult) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *QueryResult) GetStatus() *SyncStatus {
	if x != nil {
		return x.Status
	}
	return nil
}

type Command struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Kind          string                 `protobuf:"bytes,3,opt,name=kind,proto3" json:"kind,omitempty"`
	From          int64                  `protobuf:"varint,4,opt,name=from,proto3" json:"from,omitempty"`
	To            int64                  `protobuf:"varint,5,opt,name=to,proto3" json:"to,omitempty"`
	InitialDays   int32                  `protobuf:"varint,6,opt,name=initial_days,json=initialDays,proto3" json:"initial_days,omitempty"`
	RetentionDays int32                  `protobuf:"varint,7,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_api_proto_services_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{15}
}

func (x *Command) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *Command) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Command) GetKind() string {
	if x != nil {
		return x.Kind
	}
	return ""
}

func (x *Command) GetFrom() int64 {
	if x != nil {
		return x.From
	}
	return 0
}

func (x *Command) GetTo() int64 {
	if x != nil {
		return x.To
	}
	return 0
}

func (x *Command) GetInitialDays() int32 {
	if x != nil {
		return x.InitialDays
	}
	return 0
}

func (x *Command) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

type Operation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	State         string                 `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	ErrorCode     string                 `protobuf:"bytes,4,opt,name=error_code,json=errorCode,proto3" json:"error_code,omitempty"`
	Processed     int64                  `protobuf:"varint,5,opt,name=processed,proto3" json:"processed,omitempty"`
	Inserted      int64                  `protobuf:"varint,6,opt,name=inserted,proto3" json:"inserted,omitempty"`
	Updated       int64                  `protobuf:"varint,7,opt,name=updated,proto3" json:"updated,omitempty"`
	Deduplicated  int64                  `protobuf:"varint,8,opt,name=deduplicated,proto3" json:"deduplicated,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Operation) Reset() {
	*x = Operation{}
	mi := &file_api_proto_services_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Operation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Operation) ProtoMessage() {}

func (x *Operation) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Operation.ProtoReflect.Descriptor instead.
func (*Operation) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{16}
}

func (x *Operation) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Operation) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *Operation) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Operation) GetErrorCode() string {
	if x != nil {
		return x.ErrorCode
	}
	return ""
}

func (x *Operation) GetProcessed() int64 {
	if x != nil {
		return x.Processed
	}
	return 0
}

func (x *Operation) GetInserted() int64 {
	if x != nil {
		return x.Inserted
	}
	return 0
}

func (x *Operation) GetUpdated() int64 {
	if x != nil {
		return x.Updated
	}
	return 0
}

func (x *Operation) GetDeduplicated() int64 {
	if x != nil {
		return x.Deduplicated
	}
	return 0
}

type OperationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	OperationId   string                 `protobuf:"bytes,2,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationRequest) Reset() {
	*x = OperationRequest{}
	mi := &file_api_proto_services_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationRequest) ProtoMessage() {}

func (x *OperationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationRequest.ProtoReflect.Descriptor instead.
func (*OperationRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{17}
}

func (x *OperationRequest) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *OperationRequest) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type Settings struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InitialDays   int32                  `protobuf:"varint,1,opt,name=initial_days,json=initialDays,proto3" json:"initial_days,omitempty"`
	RetentionDays int32                  `protobuf:"varint,2,opt,name=retention_days,json=retentionDays,proto3" json:"retention_days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Settings) Reset() {
	*x = Settings{}
	mi := &file_api_proto_services_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Settings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Settings) ProtoMessage() {}

func (x *Settings) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Settings.ProtoReflect.Descriptor instead.
func (*Settings) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{18}
}

func (x *Settings) GetInitialDays() int32 {
	if x != nil {
		return x.InitialDays
	}
	return 0
}

func (x *Settings) GetRetentionDays() int32 {
	if x != nil {
		return x.RetentionDays
	}
	return 0
}

type SettingsCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Auth          *Auth                  `protobuf:"bytes,1,opt,name=auth,proto3" json:"auth,omitempty"`
	CommandId     string                 `protobuf:"bytes,2,opt,name=command_id,json=commandId,proto3" json:"command_id,omitempty"`
	Settings      *Settings              `protobuf:"bytes,3,opt,name=settings,proto3" json:"settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SettingsCommand) Reset() {
	*x = SettingsCommand{}
	mi := &file_api_proto_services_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SettingsCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SettingsCommand) ProtoMessage() {}

func (x *SettingsCommand) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SettingsCommand.ProtoReflect.Descriptor instead.
func (*SettingsCommand) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{19}
}

func (x *SettingsCommand) GetAuth() *Auth {
	if x != nil {
		return x.Auth
	}
	return nil
}

func (x *SettingsCommand) GetCommandId() string {
	if x != nil {
		return x.CommandId
	}
	return ""
}

func (x *SettingsCommand) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

type Panel struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Users         []*User                `protobuf:"bytes,1,rep,name=users,proto3" json:"users,omitempty"`
	Timezone      string                 `protobuf:"bytes,2,opt,name=timezone,proto3" json:"timezone,omitempty"`
	Data          *QueryResult           `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Settings      *Settings              `protobuf:"bytes,4,opt,name=settings,proto3" json:"settings,omitempty"`
	Coverage      string                 `protobuf:"bytes,5,opt,name=coverage,proto3" json:"coverage,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Panel) Reset() {
	*x = Panel{}
	mi := &file_api_proto_services_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Panel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Panel) ProtoMessage() {}

func (x *Panel) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Panel.ProtoReflect.Descriptor instead.
func (*Panel) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{20}
}

func (x *Panel) GetUsers() []*User {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *Panel) GetTimezone() string {
	if x != nil {
		return x.Timezone
	}
	return ""
}

func (x *Panel) GetData() *QueryResult {
	if x != nil {
		return x.Data
	}
	return nil
}

func (x *Panel) GetSettings() *Settings {
	if x != nil {
		return x.Settings
	}
	return nil
}

func (x *Panel) GetCoverage() string {
	if x != nil {
		return x.Coverage
	}
	return ""
}

// Core-only OAuth discovery. mTLS core identity is mandatory. The transient
// candidate credential is never persisted or exposed to Activity/CRM Events.
type BootstrapAccountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	IntegrationId string                 `protobuf:"bytes,1,opt,name=integration_id,json=integrationId,proto3" json:"integration_id,omitempty"`
	AccountDomain string                 `protobuf:"bytes,2,opt,name=account_domain,json=accountDomain,proto3" json:"account_domain,omitempty"`
	AccessToken   string                 `protobuf:"bytes,3,opt,name=access_token,json=accessToken,proto3" json:"access_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapAccountRequest) Reset() {
	*x = BootstrapAccountRequest{}
	mi := &file_api_proto_services_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapAccountRequest) ProtoMessage() {}

func (x *BootstrapAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapAccountRequest.ProtoReflect.Descriptor instead.
func (*BootstrapAccountRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{21}
}

func (x *BootstrapAccountRequest) GetIntegrationId() string {
	if x != nil {
		return x.IntegrationId
	}
	return ""
}

func (x *BootstrapAccountRequest) GetAccountDomain() string {
	if x != nil {
		return x.AccountDomain
	}
	return ""
}

func (x *BootstrapAccountRequest) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

type BootstrapAccount struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Subdomain     string                 `protobuf:"bytes,2,opt,name=subdomain,proto3" json:"subdomain,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BootstrapAccount) Reset() {
	*x = BootstrapAccount{}
	mi := &file_api_proto_services_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BootstrapAccount) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BootstrapAccount) ProtoMessage() {}

func (x *BootstrapAccount) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_services_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BootstrapAccount.ProtoReflect.Descriptor instead.
func (*BootstrapAccount) Descriptor() ([]byte, []int) {
	return file_api_proto_services_proto_rawDescGZIP(), []int{22}
}

func (x *BootstrapAccount) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *BootstrapAccount) GetSubdomain() string {
	if x != nil {
		return x.Subdomain
	}
	return ""
}

var File_api_proto_services_proto protoreflect.FileDescriptor

const file_api_proto_services_proto_rawDesc = "" +
	"\n" +
	"\x18api/proto/services.proto\x12\x12amocrm.services.v1\"\x1c\n" +
	"\x04Auth\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\";\n" +
	"\x05Grant\x12\x1a\n" +
	"\baudience\x18\x01 \x01(\tR\baudience\x12\x16\n" +
	"\x06action\x18\x02 \x01(\tR\x06action\"\xff\x01\n" +
	"\fIssueRequest\x12%\n" +
	"\x0eintegration_id\x18\x01 \x01(\tR\rintegrationId\x12'\n" +
	"\x0finstallation_id\x18\x02 \x01(\tR\x0einstallationId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\x03R\aactorId\x12\x16\n" +
	"\x06system\x18\x04 \x01(\bR\x06system\x12\x1a\n" +
	"\bconsumer\x18\x05 \x01(\tR\bconsumer\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x121\n" +
	"\x06grants\x18\a \x03(\v2\x19.amocrm.services.v1.GrantR\x06grants\"s\n" +
	"\x0fValidateRequest\x12,\n" +
	"\x04auth\x18\x01 \x01(\v2\x18.amocrm.services.v1.AuthR\x04auth\x12\x1a\n" +
	"\baudience\x18\x02 \x01(\tR\baudience\x12\x16\n" +
	"\x06action\x18\x03 \x01(\tR\x06action\"\xe8\x01\n" +
	"\tPrincipal\x12%\n" +
	"\x0eintegration_id\x18\x01 \x01(\tR\rintegrationId\x12'\n" +
	"\x0finstallation_id\x18\x02 \x01(\tR\x0einstallationId\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\x03R\aactorId\x12\x16\n" +
	"\x06system\x18\x04 \x01(\bR\x06system\x12\x1a\n" +
	"\bconsumer\x18\x05 \x01(\tR\bconsumer\x12\x1d\n" +
	"\n" +
	"request_id\x18\x06 \x01(\tR\trequestId\x12\x1d\n" +
	"\n" +
	"expires_at\x18\a \x01(\tR\texpiresAt\"\xeb\x01\n" +
	"\x05Event\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"created_at\x18\x02 \x01(\x03R\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x03 \x01(\x03R\tcreatedBy\x12\x12\n" +
	"\x04type\x18\x04 \x01(\tR\x04type\x12\x1b\n" +
	"\tentity_id\x18\x05 \x01(\x03R\bentityId\x12\x1f\n" +
	"\ventity_type\x18\x06 \x01(\tR\n" +
	"entityType\x12!\n" +
	"\fvalue_before\x18\a \x01(\fR\vvalueBefore\x12\x1f\n" +
	"\vvalue_after\x18\b \x01(\fR\n" +
	"valueAfter\"\x8e\x01\n" +
	"\x10EventPageRequest\x12,\n" +
	"\x04auth\x18\x01 \x01(\v2\x18.amocrm.services.v1.AuthR\x04auth\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x03R\x02to\x12\x12\n" +
	"\x04page\x18\x04 \x01(\x05R\x04page\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\"Y\n" +
	"\tEventPage\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.amocrm.services.v1.EventR\x06events\x12\x19\n" +
	"\bhas_next\x18\x02 \x01(\bR\ahasNext\"d\n" +
	"\x04User\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x19\n" +
	"\bgroup_id\x18\x03 \x01(\x03R\agroupId\x12\x1d\n" +
	"\n" +
	"group_name\x18\x04 \x01(\tR\tgroupName\"W\n" +
	"\fUsersRequest\x12,\n" +
	"\x04auth\x18\x01 \x01(\v2\x18.amocrm.services.v1.AuthR\x04auth\x12\x19\n" +
	"\buser_ids\x18\x02 \x03(\x03R\auserIds\"W\n" +
	"\tDirectory\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.amocrm.services.v1.UserR\x05users\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\"\xa2\x01\n" +
	"\x05Query\x12,\n" +
	"\x04auth\x18\x01 \x01(\v2\x18.amocrm.services.v1.AuthR\x04auth\x12\x12\n" +
	"\x04from\x18\x02 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x03 \x01(\x03R\x02to\x12\x19\n" +
	"\buser_ids\x18\x04 \x03(\x03R\auserIds\x12\x14\n" +
	"\x05limit\x18\x05 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06cursor\x18\x06 \x01(\tR\x06cursor\"o\n" +
	"\vUserSummary\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\x03R\x06userId\x12#\n" +
	"\runique_events\x18\x02 \x01(\x03R\funiqueEvents\x12\"\n" +
	"\rlast_event_at\x18\x03 \x01(\x03R\vlastEventAt\"\xe3\x03\n" +
	"\n" +
	"SyncStatus\x12\x18\n" +
	"\aenabled\x18\x01 \x01(\bR\aenabled\x12\x14\n" +
	"\x05state\x18\x02 \x01(\tR\x05state\x12!\n" +
	"\fhistory_from\x18\x03 \x01(\x03R\vhistoryFrom\x12#\n" +
	"\rverified_from\x18\x04 \x01(\x03R\fverifiedFrom\x12)\n" +
	"\x10verified_through\x18\x05 \x01(\x03R\x0fverifiedThrough\x12\x1f\n" +
	"\vwindow_from\x18\x06 \x01(\x03R\n" +
	"windowFrom\x12\x1b\n" +
	"\twindow_to\x18\a \x01(\x03R\bwindowTo\x12\x1b\n" +
	"\tnext_page\x18\b \x01(\x05R\bnextPage\x12&\n" +
	"\x0flast_success_at\x18\t \x01(\x03R\rlastSuccessAt\x12\"\n" +
	"\rlast_event_at\x18\n" +
	" \x01(\x03R\vlastEventAt\x12\x1f\n" +
	"\vlag_seconds\x18\v \x01(\x03R\n" +
	"lagSeconds\x12\x1d\n" +
	"\n" +
	"error_code\x18\f \x01(\tR\terrorCode\x12'\n" +
	"\x0freauth_required\x18\r \x01(\bR\x0ereauthRequired\x12\"\n" +
	"\fverification\x18\x0e \x01(\tR\fverification\"\xd8\x01\n" +
	"\vQueryResult\x121\n" +
	"\x06events\x18\x01 \x03(\v2\x19.amocrm.services.v1.EventR\x06events\x12=\n" +
	"\tsummaries\x18\x02 \x03(\v2\x1f.amocrm.services.v1.UserSummaryR\tsummaries\x12\x1f\n" +
	"\vnext_cursor\x18\x03 \x01(\tR\n" +
	"nextCursor\x126\n" +
	"\x06status\x18\x04 \x01(\v2\x1e.amocrm.services.v1.SyncStatusR\x06status\"\xd8\x01\n" +
	"\aCommand\x12,\n" +
	"\x04auth\x18\x01 \x01(\v2\x18.amocrm.services.v1.AuthR\x04auth\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x12\n" +
	"\x04kind\x18\x03 \x01(\tR\x04kind\x12\x12\n" +
	"\x04from\x18\x04 \x01(\x03R\x04from\x12\x0e\n" +
	"\x02to\x18\x05 \x01(\x03R\x02to\x12!\n" +
	"\finitial_days\x18\x06 \x01(\x05R\vinitialDays\x12%\n" +
	"\x0eretention_days\x18\a \x01(\x05R\rretentionDays\"\xe7\x01\n" +
	"\tOperation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12\x1d\n" +
	"\n" +
	"error_code\x18\x04 \x01(\tR\terrorCode\x12\x1c\n" +
	"\tprocessed\x18\x05 \x01(\x03R\tprocessed\x12\x1a\n" +
	"\binserted\x18\x06 \x01(\x03R\binserted\x12\x18\n" +
	"\aupdated\x18\a \x01(\x03R\aupdated\x12\"\n" +
	"\fdeduplicated\x18\b \x01(\x03R\fdeduplicated\"c\n" +
	"\x10OperationRequest\x12,\n" +
	"\x04auth\x18\x01 \x01(\v2\x18.amocrm.services.v1.AuthR\x04auth\x12!\n" +
	"\foperation_id\x18\x02 \x01(\tR\voperationId\"T\n" +
	"\bSettings\x12!\n" +
	"\finitial_days\x18\x01 \x01(\x05R\vinitialDays\x12%\n" +
	"\x0eretention_days\x18\x02 \x01(\x05R\rretentionDays\"\x98\x01\n" +
	"\x0fSettingsCommand\x12,\n" +
	"\x04auth\x18\x01 \x01(\v2\x18.amocrm.services.v1.AuthR\x04auth\x12\x1d\n" +
	"\n" +
	"command_id\x18\x02 \x01(\tR\tcommandId\x128\n" +
	"\bsettings\x18\x03 \x01(\v2\x1c.amocrm.services.v1.SettingsR\bsettings\"\xde\x01\n" +
	"\x05Panel\x12.\n" +
	"\x05users\x18\x01 \x03(\v2\x18.amocrm.services.v1.UserR\x05users\x12\x1a\n" +
	"\btimezone\x18\x02 \x01(\tR\btimezone\x123\n" +
	"\x04data\x18\x03 \x01(\v2\x1f.amocrm.services.v1.QueryResultR\x04data\x128\n" +
	"\bsettings\x18\x04 \x01(\v2\x1c.amocrm.services.v1.SettingsR\bsettings\x12\x1a\n" +
	"\bcoverage\x18\x05 \x01(\tR\bcoverage\"\x8a\x01\n" +
	"\x17BootstrapAccountRequest\x12%\n" +
	"\x0eintegration_id\x18\x01 \x01(\tR\rintegrationId\x12%\n" +
	"\x0eaccount_domain\x18\x02 \x01(\tR\raccountDomain\x12!\n" +
	"\faccess_token\x18\x03 \x01(\tR\vaccessToken\"@\n" +
	"\x10BootstrapAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x1c\n" +
	"\tsubdomain\x18\x02 \x01(\tR\tsubdomain2\x9d\x01\n" +
	"\x06Policy\x12C\n" +
	"\x05Issue\x12 .amocrm.services.v1.IssueRequest\x1a\x18.amocrm.services.v1.Auth\x12N\n" +
	"\bValidate\x12#.amocrm.services.v1.ValidateRequest\x1a\x1d.amocrm.services.v1.Principal2\xa2\x01\n" +
	"\aGateway\x12M\n" +
	"\x06Events\x12$.amocrm.services.v1.EventPageRequest\x1a\x1d.amocrm.services.v1.EventPage\x12H\n" +
	"\x05Users\x12 .amocrm.services.v1.UsersRequest\x1a\x1d.amocrm.services.v1.Directory2\xb7\x02\n" +
	"\tCRMEvents\x12C\n" +
	"\x05Apply\x12\x1b.amocrm.services.v1.Command\x1a\x1d.amocrm.services.v1.Operation\x12I\n" +
	"\vQueryEvents\x12\x19.amocrm.services.v1.Query\x1a\x1f.amocrm.services.v1.QueryResult\x12B\n" +
	"\x06Status\x12\x18.amocrm.services.v1.Auth\x1a\x1e.amocrm.services.v1.SyncStatus\x12V\n" +
	"\x0fOperationStatus\x12$.amocrm.services.v1.OperationRequest\x1a\x1d.amocrm.services.v1.Operation2\xbc\x02\n" +
	"\bActivity\x12@\n" +
	"\bGetPanel\x12\x19.amocrm.services.v1.Query\x1a\x19.amocrm.services.v1.Panel\x12E\n" +
	"\vGetSettings\x12\x18.amocrm.services.v1.Auth\x1a\x1c.amocrm.services.v1.Settings\x12O\n" +
	"\tConfigure\x12#.amocrm.services.v1.SettingsCommand\x1a\x1d.amocrm.services.v1.Operation\x12V\n" +
	"\x0fOperationStatus\x12$.amocrm.services.v1.OperationRequest\x1a\x1d.amocrm.services.v1.Operation2p\n" +
	"\rCoreBootstrap\x12_\n" +
	"\n" +
	"GetAccount\x12+.amocrm.services.v1.BootstrapAccountRequest\x1a$.amocrm.services.v1.BootstrapAccountB4Z2github.com/sk1fy/amocrm-pro/internal/servicerpc/pbb\x06proto3"

var (
	file_api_proto_services_proto_rawDescOnce sync.Once
	file_api_proto_services_proto_rawDescData []byte
)

func file_api_proto_services_proto_rawDescGZIP() []byte {
	file_api_proto_services_proto_rawDescOnce.Do(func() {
		file_api_proto_services_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_services_proto_rawDesc), len(file_api_proto_services_proto_rawDesc)))
	})
	return file_api_proto_services_proto_rawDescData
}

var file_api_proto_services_proto_msgTypes = make([]protoimpl.MessageInfo, 23)
var file_api_proto_services_proto_goTypes = []any{
	(*Auth)(nil),                    // 0: amocrm.services.v1.Auth
	(*Grant)(nil),                   // 1: amocrm.services.v1.Grant
	(*IssueRequest)(nil),            // 2: amocrm.services.v1.IssueRequest
	(*ValidateRequest)(nil),         // 3: amocrm.services.v1.ValidateRequest
	(*Principal)(nil),               // 4: amocrm.services.v1.Principal
	(*Event)(nil),                   // 5: amocrm.services.v1.Event
	(*EventPageRequest)(nil),        // 6: amocrm.services.v1.EventPageRequest
	(*EventPage)(nil),               // 7: amocrm.services.v1.EventPage
	(*User)(nil),                    // 8: amocrm.services.v1.User
	(*UsersRequest)(nil),            // 9: amocrm.services.v1.UsersRequest
	(*Directory)(nil),               // 10: amocrm.services.v1.Directory
	(*Query)(nil),                   // 11: amocrm.services.v1.Query
	(*UserSummary)(nil),             // 12: amocrm.services.v1.UserSummary
	(*SyncStatus)(nil),              // 13: amocrm.services.v1.SyncStatus
	(*QueryResult)(nil),             // 14: amocrm.services.v1.QueryResult
	(*Command)(nil),                 // 15: amocrm.services.v1.Command
	(*Operation)(nil),               // 16: amocrm.services.v1.Operation
	(*OperationRequest)(nil),        // 17: amocrm.services.v1.OperationRequest
	(*Settings)(nil),                // 18: amocrm.services.v1.Settings
	(*SettingsCommand)(nil),         // 19: amocrm.services.v1.SettingsCommand
	(*Panel)(nil),                   // 20: amocrm.services.v1.Panel
	(*BootstrapAccountRequest)(nil), // 21: amocrm.services.v1.BootstrapAccountRequest
	(*BootstrapAccount)(nil),        // 22: amocrm.services.v1.BootstrapAccount
}
var file_api_proto_services_proto_depIdxs = []int32{
	1,  // 0: amocrm.services.v1.IssueRequest.grants:type_name -> amocrm.services.v1.Grant
	0,  // 1: amocrm.services.v1.ValidateRequest.auth:type_name -> amocrm.services.v1.Auth
	0,  // 2: amocrm.services.v1.EventPageRequest.auth:type_name -> amocrm.services.v1.Auth
	5,  // 3: amocrm.services.v1.EventPage.events:type_name -> amocrm.services.v1.Event
	0,  // 4: amocrm.services.v1.UsersRequest.auth:type_name -> amocrm.services.v1.Auth
	8,  // 5: amocrm.services.v1.Directory.users:type_name -> amocrm.services.v1.User
	0,  // 6: amocrm.services.v1.Query.auth:type_name -> amocrm.services.v1.Auth
	5,  // 7: amocrm.services.v1.QueryResult.events:type_name -> amocrm.services.v1.Event
	12, // 8: amocrm.services.v1.QueryResult.summaries:type_name -> amocrm.services.v1.UserSummary
	13, // 9: amocrm.services.v1.QueryResult.status:type_name -> amocrm.services.v1.SyncStatus
	0,  // 10: amocrm.services.v1.Command.auth:type_name -> amocrm.services.v1.Auth
	0,  // 11: amocrm.services.v1.OperationRequest.auth:type_name -> amocrm.services.v1.Auth
	0,  // 12: amocrm.services.v1.SettingsCommand.auth:type_name -> amocrm.services.v1.Auth
	18, // 13: amocrm.services.v1.SettingsCommand.settings:type_name -> amocrm.services.v1.Settings
	8,  // 14: amocrm.services.v1.Panel.users:type_name -> amocrm.services.v1.User
	14, // 15: amocrm.services.v1.Panel.data:type_name -> amocrm.services.v1.QueryResult
	18, // 16: amocrm.services.v1.Panel.settings:type_name -> amocrm.services.v1.Settings
	2,  // 17: amocrm.services.v1.Policy.Issue:input_type -> amocrm.services.v1.IssueRequest
	3,  // 18: amocrm.services.v1.Policy.Validate:input_type -> amocrm.services.v1.ValidateRequest
	6,  // 19: amocrm.services.v1.Gateway.Events:input_type -> amocrm.services.v1.EventPageRequest
	9,  // 20: amocrm.services.v1.Gateway.Users:input_type -> amocrm.services.v1.UsersRequest
	15, // 21: amocrm.services.v1.CRMEvents.Apply:input_type -> amocrm.services.v1.Command
	11, // 22: amocrm.services.v1.CRMEvents.QueryEvents:input_type -> amocrm.services.v1.Query
	0,  // 23: amocrm.services.v1.CRMEvents.Status:input_type -> amocrm.services.v1.Auth
	17, // 24: amocrm.services.v1.CRMEvents.OperationStatus:input_type -> amocrm.services.v1.OperationRequest
	11, // 25: amocrm.services.v1.Activity.GetPanel:input_type -> amocrm.services.v1.Query
	0,  // 26: amocrm.services.v1.Activity.GetSettings:input_type -> amocrm.services.v1.Auth
	19, // 27: amocrm.services.v1.Activity.Configure:input_type -> amocrm.services.v1.SettingsCommand
	17, // 28: amocrm.services.v1.Activity.OperationStatus:input_type -> amocrm.services.v1.OperationRequest
	21, // 29: amocrm.services.v1.CoreBootstrap.GetAccount:input_type -> amocrm.services.v1.BootstrapAccountRequest
	0,  // 30: amocrm.services.v1.Policy.Issue:output_type -> amocrm.services.v1.Auth
	4,  // 31: amocrm.services.v1.Policy.Validate:output_type -> amocrm.services.v1.Principal
	7,  // 32: amocrm.services.v1.Gateway.Events:output_type -> amocrm.services.v1.EventPage
	10, // 33: amocrm.services.v1.Gateway.Users:output_type -> amocrm.services.v1.Directory
	16, // 34: amocrm.services.v1.CRMEvents.Apply:output_type -> amocrm.services.v1.Operation
	14, // 35: amocrm.services.v1.CRMEvents.QueryEvents:output_type -> amocrm.services.v1.QueryResult
	13, // 36: amocrm.services.v1.CRMEvents.Status:output_type -> amocrm.services.v1.SyncStatus
	16, // 37: amocrm.services.v1.CRMEvents.OperationStatus:output_type -> amocrm.services.v1.Operation
	20, // 38: amocrm.services.v1.Activity.GetPanel:output_type -> amocrm.services.v1.Panel
	18, // 39: amocrm.services.v1.Activity.GetSettings:output_type -> amocrm.services.v1.Settings
	16, // 40: amocrm.services.v1.Activity.Configure:output_type -> amocrm.services.v1.Operation
	16, // 41: amocrm.services.v1.Activity.OperationStatus:output_type -> amocrm.services.v1.Operation
	22, // 42: amocrm.services.v1.CoreBootstrap.GetAccount:output_type -> amocrm.services.v1.BootstrapAccount
	30, // [30:43] is the sub-list for method output_type
	17, // [17:30] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_api_proto_services_proto_init() }
func file_api_proto_services_proto_init() {
	if File_api_proto_services_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_services_proto_rawDesc), len(file_api_proto_services_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   23,
			NumExtensions: 0,
			NumServices:   5,
		},
		GoTypes:           file_api_proto_services_proto_goTypes,
		DependencyIndexes: file_api_proto_services_proto_depIdxs,
		MessageInfos:      file_api_proto_services_proto_msgTypes,
	}.Build()
	File_api_proto_services_proto = out.File
	file_api_proto_services_proto_goTypes = nil
	file_api_proto_services_proto_depIdxs = nil
}
