// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.31.1
// source: api/proto/services.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Policy_Issue_FullMethodName    = "/amocrm.services.v1.Policy/Issue"
	Policy_Validate_FullMethodName = "/amocrm.services.v1.Policy/Validate"
)

// PolicyClient is the client API for Policy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type PolicyClient interface {
	Issue(ctx context.Context, in *IssueRequest, opts ...grpc.CallOption) (*Auth, error)
	Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*Principal, error)
}

type policyClient struct {
	cc grpc.ClientConnInterface
}

func NewPolicyClient(cc grpc.ClientConnInterface) PolicyClient {
	return &policyClient{cc}
}

func (c *policyClient) Issue(ctx context.Context, in *IssueRequest, opts ...grpc.CallOption) (*Auth, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Auth)
	err := c.cc.Invoke(ctx, Policy_Issue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *policyClient) Validate(ctx context.Context, in *ValidateRequest, opts ...grpc.CallOption) (*Principal, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Principal)
	err := c.cc.Invoke(ctx, Policy_Validate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PolicyServer is the server API for Policy service.
// All implementations must embed UnimplementedPolicyServer
// for forward compatibility.
type PolicyServer interface {
	Issue(context.Context, *IssueRequest) (*Auth, error)
	Validate(context.Context, *ValidateRequest) (*Principal, error)
	mustEmbedUnimplementedPolicyServer()
}

// UnimplementedPolicyServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPolicyServer struct{}

func (UnimplementedPolicyServer) Issue(context.Context, *IssueRequest) (*Auth, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Issue not implemented")
}
func (UnimplementedPolicyServer) Validate(context.Context, *ValidateRequest) (*Principal, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Validate not implemented")
}
func (UnimplementedPolicyServer) mustEmbedUnimplementedPolicyServer() {}
func (UnimplementedPolicyServer) testEmbeddedByValue()                {}

// UnsafePolicyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PolicyServer will
// result in compilation errors.
type UnsafePolicyServer interface {
	mustEmbedUnimplementedPolicyServer()
}

func RegisterPolicyServer(s grpc.ServiceRegistrar, srv PolicyServer) {
	// If the following call pancis, it indicates UnimplementedPolicyServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Policy_ServiceDesc, srv)
}

func _Policy_Issue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServer).Issue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Policy_Issue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServer).Issue(ctx, req.(*IssueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Policy_Validate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PolicyServer).Validate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Policy_Validate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PolicyServer).Validate(ctx, req.(*ValidateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Policy_ServiceDesc is the grpc.ServiceDesc for Policy service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Policy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amocrm.services.v1.Policy",
	HandlerType: (*PolicyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Issue",
			Handler:    _Policy_Issue_Handler,
		},
		{
			MethodName: "Validate",
			Handler:    _Policy_Validate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/services.proto",
}

const (
	Gateway_Events_FullMethodName = "/amocrm.services.v1.Gateway/Events"
	Gateway_Users_FullMethodName  = "/amocrm.services.v1.Gateway/Users"
)

// GatewayClient is the client API for Gateway service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GatewayClient interface {
	Events(ctx context.Context, in *EventPageRequest, opts ...grpc.CallOption) (*EventPage, error)
	Users(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*Directory, error)
}

type gatewayClient struct {
	cc grpc.ClientConnInterface
}

func NewGatewayClient(cc grpc.ClientConnInterface) GatewayClient {
	return &gatewayClient{cc}
}

func (c *gatewayClient) Events(ctx context.Context, in *EventPageRequest, opts ...grpc.CallOption) (*EventPage, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EventPage)
	err := c.cc.Invoke(ctx, Gateway_Events_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gatewayClient) Users(ctx context.Context, in *UsersRequest, opts ...grpc.CallOption) (*Directory, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Directory)
	err := c.cc.Invoke(ctx, Gateway_Users_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GatewayServer is the server API for Gateway service.
// All implementations must embed UnimplementedGatewayServer
// for forward compatibility.
type GatewayServer interface {
	Events(context.Context, *EventPageRequest) (*EventPage, error)
	Users(context.Context, *UsersRequest) (*Directory, error)
	mustEmbedUnimplementedGatewayServer()
}

// UnimplementedGatewayServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedGatewayServer struct{}

func (UnimplementedGatewayServer) Events(context.Context, *EventPageRequest) (*EventPage, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Events not implemented")
}
func (UnimplementedGatewayServer) Users(context.Context, *UsersRequest) (*Directory, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Users not implemented")
}
func (UnimplementedGatewayServer) mustEmbedUnimplementedGatewayServer() {}
func (UnimplementedGatewayServer) testEmbeddedByValue()                 {}

// UnsafeGatewayServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GatewayServer will
// result in compilation errors.
type UnsafeGatewayServer interface {
	mustEmbedUnimplementedGatewayServer()
}

func RegisterGatewayServer(s grpc.ServiceRegistrar, srv GatewayServer) {
	// If the following call pancis, it indicates UnimplementedGatewayServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Gateway_ServiceDesc, srv)
}

func _Gateway_Events_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EventPageRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Events(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_Events_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Events(ctx, req.(*EventPageRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Gateway_Users_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UsersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GatewayServer).Users(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Gateway_Users_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GatewayServer).Users(ctx, req.(*UsersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Gateway_ServiceDesc is the grpc.ServiceDesc for Gateway service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Gateway_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amocrm.services.v1.Gateway",
	HandlerType: (*GatewayServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Events",
			Handler:    _Gateway_Events_Handler,
		},
		{
			MethodName: "Users",
			Handler:    _Gateway_Users_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/services.proto",
}

const (
	CRMEvents_Apply_FullMethodName           = "/amocrm.services.v1.CRMEvents/Apply"
	CRMEvents_QueryEvents_FullMethodName     = "/amocrm.services.v1.CRMEvents/QueryEvents"
	CRMEvents_Status_FullMethodName          = "/amocrm.services.v1.CRMEvents/Status"
	CRMEvents_OperationStatus_FullMethodName = "/amocrm.services.v1.CRMEvents/OperationStatus"
)

// CRMEventsClient is the client API for CRMEvents service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CRMEventsClient interface {
	Apply(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Operation, error)
	QueryEvents(ctx context.Context, in *Query, opts ...grpc.CallOption) (*QueryResult, error)
	Status(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*SyncStatus, error)
	OperationStatus(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*Operation, error)
}

type cRMEventsClient struct {
	cc grpc.ClientConnInterface
}

func NewCRMEventsClient(cc grpc.ClientConnInterface) CRMEventsClient {
	return &cRMEventsClient{cc}
}

func (c *cRMEventsClient) Apply(ctx context.Context, in *Command, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, CRMEvents_Apply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRMEventsClient) QueryEvents(ctx context.Context, in *Query, opts ...grpc.CallOption) (*QueryResult, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueryResult)
	err := c.cc.Invoke(ctx, CRMEvents_QueryEvents_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRMEventsClient) Status(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*SyncStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SyncStatus)
	err := c.cc.Invoke(ctx, CRMEvents_Status_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *cRMEventsClient) OperationStatus(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, CRMEvents_OperationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CRMEventsServer is the server API for CRMEvents service.
// All implementations must embed UnimplementedCRMEventsServer
// for forward compatibility.
type CRMEventsServer interface {
	Apply(context.Context, *Command) (*Operation, error)
	QueryEvents(context.Context, *Query) (*QueryResult, error)
	Status(context.Context, *Auth) (*SyncStatus, error)
	OperationStatus(context.Context, *OperationRequest) (*Operation, error)
	mustEmbedUnimplementedCRMEventsServer()
}

// UnimplementedCRMEventsServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCRMEventsServer struct{}

func (UnimplementedCRMEventsServer) Apply(context.Context, *Command) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Apply not implemented")
}
func (UnimplementedCRMEventsServer) QueryEvents(context.Context, *Query) (*QueryResult, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryEvents not implemented")
}
func (UnimplementedCRMEventsServer) Status(context.Context, *Auth) (*SyncStatus, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Status not implemented")
}
func (UnimplementedCRMEventsServer) OperationStatus(context.Context, *OperationRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OperationStatus not implemented")
}
func (UnimplementedCRMEventsServer) mustEmbedUnimplementedCRMEventsServer() {}
func (UnimplementedCRMEventsServer) testEmbeddedByValue()                   {}

// UnsafeCRMEventsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CRMEventsServer will
// result in compilation errors.
type UnsafeCRMEventsServer interface {
	mustEmbedUnimplementedCRMEventsServer()
}

func RegisterCRMEventsServer(s grpc.ServiceRegistrar, srv CRMEventsServer) {
	// If the following call pancis, it indicates UnimplementedCRMEventsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CRMEvents_ServiceDesc, srv)
}

func _CRMEvents_Apply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Command)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRMEventsServer).Apply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRMEvents_Apply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRMEventsServer).Apply(ctx, req.(*Command))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRMEvents_QueryEvents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRMEventsServer).QueryEvents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRMEvents_QueryEvents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRMEventsServer).QueryEvents(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRMEvents_Status_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Auth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRMEventsServer).Status(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRMEvents_Status_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRMEventsServer).Status(ctx, req.(*Auth))
	}
	return interceptor(ctx, in, info, handler)
}

func _CRMEvents_OperationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CRMEventsServer).OperationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CRMEvents_OperationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CRMEventsServer).OperationStatus(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CRMEvents_ServiceDesc is the grpc.ServiceDesc for CRMEvents service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CRMEvents_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amocrm.services.v1.CRMEvents",
	HandlerType: (*CRMEventsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Apply",
			Handler:    _CRMEvents_Apply_Handler,
		},
		{
			MethodName: "QueryEvents",
			Handler:    _CRMEvents_QueryEvents_Handler,
		},
		{
			MethodName: "Status",
			Handler:    _CRMEvents_Status_Handler,
		},
		{
			MethodName: "OperationStatus",
			Handler:    _CRMEvents_OperationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/services.proto",
}

const (
	Activity_GetPanel_FullMethodName        = "/amocrm.services.v1.Activity/GetPanel"
	Activity_GetSettings_FullMethodName     = "/amocrm.services.v1.Activity/GetSettings"
	Activity_Configure_FullMethodName       = "/amocrm.services.v1.Activity/Configure"
	Activity_OperationStatus_FullMethodName = "/amocrm.services.v1.Activity/OperationStatus"
)

// ActivityClient is the client API for Activity service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ActivityClient interface {
	GetPanel(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Panel, error)
	GetSettings(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*Settings, error)
	Configure(ctx context.Context, in *SettingsCommand, opts ...grpc.CallOption) (*Operation, error)
	OperationStatus(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*Operation, error)
}

type activityClient struct {
	cc grpc.ClientConnInterface
}

func NewActivityClient(cc grpc.ClientConnInterface) ActivityClient {
	return &activityClient{cc}
}

func (c *activityClient) GetPanel(ctx context.Context, in *Query, opts ...grpc.CallOption) (*Panel, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Panel)
	err := c.cc.Invoke(ctx, Activity_GetPanel_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) GetSettings(ctx context.Context, in *Auth, opts ...grpc.CallOption) (*Settings, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Settings)
	err := c.cc.Invoke(ctx, Activity_GetSettings_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) Configure(ctx context.Context, in *SettingsCommand, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, Activity_Configure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *activityClient) OperationStatus(ctx context.Context, in *OperationRequest, opts ...grpc.CallOption) (*Operation, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Operation)
	err := c.cc.Invoke(ctx, Activity_OperationStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ActivityServer is the server API for Activity service.
// All implementations must embed UnimplementedActivityServer
// for forward compatibility.
type ActivityServer interface {
	GetPanel(context.Context, *Query) (*Panel, error)
	GetSettings(context.Context, *Auth) (*Settings, error)
	Configure(context.Context, *SettingsCommand) (*Operation, error)
	OperationStatus(context.Context, *OperationRequest) (*Operation, error)
	mustEmbedUnimplementedActivityServer()
}

// UnimplementedActivityServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedActivityServer struct{}

func (UnimplementedActivityServer) GetPanel(context.Context, *Query) (*Panel, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPanel not implemented")
}
func (UnimplementedActivityServer) GetSettings(context.Context, *Auth) (*Settings, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSettings not implemented")
}
func (UnimplementedActivityServer) Configure(context.Context, *SettingsCommand) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Configure not implemented")
}
func (UnimplementedActivityServer) OperationStatus(context.Context, *OperationRequest) (*Operation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method OperationStatus not implemented")
}
func (UnimplementedActivityServer) mustEmbedUnimplementedActivityServer() {}
func (UnimplementedActivityServer) testEmbeddedByValue()                  {}

// UnsafeActivityServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ActivityServer will
// result in compilation errors.
type UnsafeActivityServer interface {
	mustEmbedUnimplementedActivityServer()
}

func RegisterActivityServer(s grpc.ServiceRegistrar, srv ActivityServer) {
	// If the following call pancis, it indicates UnimplementedActivityServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Activity_ServiceDesc, srv)
}

func _Activity_GetPanel_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Query)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).GetPanel(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_GetPanel_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).GetPanel(ctx, req.(*Query))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_GetSettings_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Auth)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).GetSettings(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_GetSettings_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).GetSettings(ctx, req.(*Auth))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_Configure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SettingsCommand)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).Configure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_Configure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).Configure(ctx, req.(*SettingsCommand))
	}
	return interceptor(ctx, in, info, handler)
}

func _Activity_OperationStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(OperationRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ActivityServer).OperationStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Activity_OperationStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ActivityServer).OperationStatus(ctx, req.(*OperationRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Activity_ServiceDesc is the grpc.ServiceDesc for Activity service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Activity_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amocrm.services.v1.Activity",
	HandlerType: (*ActivityServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetPanel",
			Handler:    _Activity_GetPanel_Handler,
		},
		{
			MethodName: "GetSettings",
			Handler:    _Activity_GetSettings_Handler,
		},
		{
			MethodName: "Configure",
			Handler:    _Activity_Configure_Handler,
		},
		{
			MethodName: "OperationStatus",
			Handler:    _Activity_OperationStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/services.proto",
}

const (
	CoreBootstrap_GetAccount_FullMethodName = "/amocrm.services.v1.CoreBootstrap/GetAccount"
)

// CoreBootstrapClient is the client API for CoreBootstrap service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CoreBootstrapClient interface {
	GetAccount(ctx context.Context, in *BootstrapAccountRequest, opts ...grpc.CallOption) (*BootstrapAccount, error)
}

type coreBootstrapClient struct {
	cc grpc.ClientConnInterface
}

func NewCoreBootstrapClient(cc grpc.ClientConnInterface) CoreBootstrapClient {
	return &coreBootstrapClient{cc}
}

func (c *coreBootstrapClient) GetAccount(ctx context.Context, in *BootstrapAccountRequest, opts ...grpc.CallOption) (*BootstrapAccount, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BootstrapAccount)
	err := c.cc.Invoke(ctx, CoreBootstrap_GetAccount_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CoreBootstrapServer is the server API for CoreBootstrap service.
// All implementations must embed UnimplementedCoreBootstrapServer
// for forward compatibility.
type CoreBootstrapServer interface {
	GetAccount(context.Context, *BootstrapAccountRequest) (*BootstrapAccount, error)
	mustEmbedUnimplementedCoreBootstrapServer()
}

// UnimplementedCoreBootstrapServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCoreBootstrapServer struct{}

func (UnimplementedCoreBootstrapServer) GetAccount(context.Context, *BootstrapAccountRequest) (*BootstrapAccount, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAccount not implemented")
}
func (UnimplementedCoreBootstrapServer) mustEmbedUnimplementedCoreBootstrapServer() {}
func (UnimplementedCoreBootstrapServer) testEmbeddedByValue()                       {}

// UnsafeCoreBootstrapServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CoreBootstrapServer will
// result in compilation errors.
type UnsafeCoreBootstrapServer interface {
	mustEmbedUnimplementedCoreBootstrapServer()
}

func RegisterCoreBootstrapServer(s grpc.ServiceRegistrar, srv CoreBootstrapServer) {
	// If the following call pancis, it indicates UnimplementedCoreBootstrapServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&CoreBootstrap_ServiceDesc, srv)
}

func _CoreBootstrap_GetAccount_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BootstrapAccountRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CoreBootstrapServer).GetAccount(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: CoreBootstrap_GetAccount_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CoreBootstrapServer).GetAccount(ctx, req.(*BootstrapAccountRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// CoreBootstrap_ServiceDesc is the grpc.ServiceDesc for CoreBootstrap service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var CoreBootstrap_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "amocrm.services.v1.CoreBootstrap",
	HandlerType: (*CoreBootstrapServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetAccount",
			Handler:    _CoreBootstrap_GetAccount_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/services.proto",
}
